# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.0
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Fire impacts simulations
#
# This notebook demonstrates the fire impacts simulation modules.
#
# It is assumed that you have a `FireImpactsProject` populated with all pre-processed data for the catchment.

# %%
import logging
logging.basicConfig(level=logging.INFO,format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

from fire_impacts.sim import rusle, aggregate_rainfall_data, debris_flow
from fire_impacts.stochastic.rainfall import get_rainfall_replicates
from fire_impacts import FireImpactsProject
from fire_impacts.context import RunContext

import matplotlib.pyplot as plt


# %% [markdown]
# ## Settings for this study
#
# These come from `study.toml`, the same file the PrepareData notebook
# read. Anything PrepareData already worked out — the fire dates, the
# recovery windows — is read back from the project rather than repeated
# here, so there is only ever one copy of it.
#
# Running the cell prints each setting and where it came from, so you can
# check the notebook is about to do what you expect.

# %%
from fire_impacts.study import load_study

study = load_study('.')
study.describe()

PROJECT_DIR = study.project.directory
CATCHMENT   = study.catchment.name
EVENT       = study.event.name
ENSEMBLE    = study.ensemble.name
N_REPLICATES = study.ensemble.num_replicates
INSPECT_REPLICATE = study.ensemble.inspect_replicate
MEAN_ANNUAL_RAINFALL = study.ensemble.mean_annual_rainfall
AVERAGE_TEMPERATURE  = study.ensemble.average_temperature

# Replicates are numbered from zero, so the one this notebook plots has
# to be less than the number generated. Checked here rather than left to
# fail as a bare IndexError several sections below, which says nothing
# about study.toml.
if INSPECT_REPLICATE >= N_REPLICATES:
    raise ValueError(
        f'ensemble.inspect_replicate is {INSPECT_REPLICATE}, but only '
        f'{N_REPLICATES} replicates are generated '
        f'(ensemble.num_replicates), numbered 0 to {N_REPLICATES - 1}. '
        f'Lower inspect_replicate or raise num_replicates in study.toml.')

# %% [markdown]
# ## Load project

# %%
proj = FireImpactsProject(PROJECT_DIR, exist_ok=True)

# %%
proj.catchments

# %% [markdown]
# > **Note:** a `FireImpactsProject` can hold several catchments. This
# > notebook works on the one named by `catchment.name` in `study.toml`.

# %%
# A simulation binds to one (catchment, event, ensemble) combination
# via a RunContext. The event must match a directory produced by
# PrepareData; the ensemble names this climate realisation. Outputs
# land under Catchments/<c>/Runs/<event>/<ensemble>/.
# What has been prepared for this catchment? A RunContext can be built for
# an event that does not exist yet — you might create the context before
# running PrepareData — so it is worth checking the names first.
proj.events(CATCHMENT)
proj.ensembles(CATCHMENT)

# %%
ctx = RunContext.solo_run(
    proj, event=EVENT, ensemble=ENSEMBLE, catchment=CATCHMENT,
)
ctx

# %% [markdown]
# > **Subcatchments.** Results are summarised over subcatchments as well
# > as the whole catchment when *PrepareData* has registered a coverage of
# > them — it does when `catchment.subcatchments` is set in `study.toml`.
# > Every simulation here runs either way; without them the subcatchment
# > summary tables are simply not written, and the `plot_subcatchments()`
# > cells further down stop with a message naming `add_subcatchments()`.

# %% [markdown]
# ## Rainfall data
#
# Both the erosion (RUSLE) and debris flow modules rely on subdaily rainfall data. The erosion modules, demonstrated here, rely on 30 minute data, while the debris flow relies on 12 minute data.
#
# Furthermore, it is encouraged that both modules be run stochastically, using multiple rainfall replicates.
#
# The library provides functionality for processing stochastic rainfall data, generated by [pyraingen](https://github.com/crdykman/pyraingen). You can install pyraingen locally and calibrate it to available subdaily rainfall observations. Alternatively, you can call a remote pyraingen API and generate data based on publicly available data. We wil use the remote API in this example.

# %%
# The fire dates and recovery windows were set during PrepareData (fire
# severity + compute_adjusted_k_c) and stored in the event's FireMeta.csv /
# event.json. The simulation period is therefore read back from the context
# (fire end date -> end of the last recovery window) rather than hard-coded.
rain_data_start, rain_data_end = ctx.simulation_period()

# `num_years` is inferred from start/end (one API year per calendar
# year spanned).  `mean_annual_rainfall` and `average_temperature` are
# optional: leave them out of study.toml and they arrive here as None,
# which tells the backend service to estimate them from the catchment's
# lat/lon.  Set them in study.toml when you have site-specific climate
# statistics.
# The generated rainfall is cached under Ensembles/<ensemble>/ and reused
# on repeat runs — identical rainfall, no repeat API call. Pass
# regenerate=True to force a fresh draw.
# Note what that means for the two climate statistics: only the window and
# the replicate count decide whether the cache is reused, so changing
# mean_annual_rainfall or average_temperature after a run has no effect
# until you pass regenerate=True. You get the cached rainfall, silently.
replicates = get_rainfall_replicates(
    ctx,
    start=rain_data_start,
    end=rain_data_end,
    num_replicates=N_REPLICATES,
    mean_annual_rainfall=MEAN_ANNUAL_RAINFALL,   # None -> estimated
    average_temperature=AVERAGE_TEMPERATURE,     # None -> estimated
)
rainfall_data = replicates
# %% [markdown]
# Once we have our pyraingen rainfall replicates, we use `aggregate_rainfall_data()` to resample the results to the 30-minute frequency required for the erosion simulations

# %%
# aggregate_rainfall_data?

# %%
rainfall_30min = aggregate_rainfall_data(rainfall_data,rain_data_start,rain_data_end)

# %%
# You can inspect the aggregated rainfal data object if required:
rainfall_30min

# %% [markdown]
# **Note:** the data just generated holds `ensemble.num_replicates`
# stochastic replicates. The examples below run just one of them — the one
# numbered `ensemble.inspect_replicate` in `study.toml`, counting from
# zero, so it must be less than `ensemble.num_replicates`. Running every
# replicate is what the *SimulationEnsemble* notebook does.
#

# %% [markdown]
# ## Erosion/RUSLE: Daily Simulation
#
# Erosion processed are modelled cell-by-cell, timestep-by-timestep.
#
# This can result in a large amount of output that in most cases is not directly usable.
#
#  The library currently multiple ways to extract data from the model as it runs via customisable 'recorders'.
#

# %%
# Grab a single rainfall sequence from the stochastic rainfall replicates and inspect it:
rain_seq = rainfall_30min.rainfall[:, INSPECT_REPLICATE].to_pandas()
rain_seq

# %% [markdown]
# ### Setting up recorders
#
# We want multiple gridded outputs:
# * Total erosion for the year following the fire (year 1),
# * Total erosion for the second year post fire
# * Peak 30 min erosion for year 1 and for year 2
# * The same stats for sediment *delivered* to streams
#
# We also want daily timeseries at the subcatchment scale that we can later import into Source. If you did not set `catchment.subcatchments` above, that timeseries covers the catchment as a single zone instead.

# %%
# Recorders are built with the default_rusle_recorders() factory: it returns
# a factory(ctx, start, end) that produces a fresh recorder set. Here we ask
# for whole-period ('total') grids of RUSLE and delivered sediment, each as a
# sum and a peak, plus a daily subcatchment timeseries. Other grid cadences
# are available: 'yearly', 'quarterly', 'monthly', 'weekly', 'daily',
# ('yearly', 'fire') for year-since-fire, or 'timestep' for a grid per model
# step. This produces keys like 'RUSLE_sum_total' and 'delivered_max_total'.
recorder_factory = rusle.default_rusle_recorders(
    grid_variables=('RUSLE', 'delivered'),
    grid_fns=('sum', 'max'),
    grid_timesteps=('total',),
    include_timeseries=True,
)
recorders = recorder_factory(ctx, rain_seq.index[0], rain_seq.index[-1])

# %%

# %% [markdown]
# ### Calibration parameters for this run
#
# The RUSLE simulation and the debris flow model have their own calibration
# parameters (`erosion` and `debris`). They resolve through the same five
# layers as the preprocessing ones — package defaults, then
# `<project>/parameters.json`, `Catchments/<c>/parameters.json`, the event's
# `event.json`, then a one-off call override — with the most specific winning.
#
# You do not need to re-specify anything the PrepareData notebook set: the
# context reads it back.
#
# > **Status:** `erosion` and `debris` are both live here — the RUSLE P
# > factor, the dNBR severity split, the kinetic-energy rate, and the
# > debris erosion/deposition coefficients all take effect. The
# > preprocessing groups are live too, so the layers this run reads
# > already reflect any overrides you set in PrepareData.

# %%
# What this run resolves, and where each value came from:
record = ctx.parameters()
record.parameters.erosion.support_practice_factor

# %%
# `sources` distinguishes a deliberate value from a defaulted one — the thing
# you will want to know when you revisit these results.
record.sources['erosion.support_practice_factor']

# %%
# `erosion` and `debris` control run-scope outputs, so unlike `topography` and
# `delivery` they can be set at any level, including per event:
# ctx.set_event_parameter_overrides({'erosion': {'support_practice_factor': 0.8}})

# %%
# ...or for a single run, without persisting anything. The resolved record
# is written to provenance.json beside the results, so the outputs say what
# produced them:
# results = rusle.run_usle_simulation(
#     ctx, rain_seq, recorders=recorders,
#     params=ctx.parameters(erosion__support_practice_factor=0.8))

# %% [markdown]
# ### Stale layer check
#
# The C/K/SDR layers this run reads were built by PrepareData. If you have
# changed a preprocessing parameter since then, the simulation raises
# rather than silently mixing two calibrations — re-run
# `compute_adjusted_k_c`, or pass `allow_stale=True` if the mismatch is
# deliberate. Only the parameters a layer depends on are compared.

# %% [markdown]
# ### Run the simulation

# %%
# run_usle_simulation runs the whole rainfall period continuously, applying
# the recovery windows internally (the fire-adjusted C/K/SDR layers switch at
# each window boundary). Recovery is not an output dimension — results are a
# single continuous set for this run.
results = rusle.run_usle_simulation(ctx, rain_seq, recorders=recorders)

# %% [markdown]
# ### Baseline (no-fire) simulation
#
# To isolate the fire-attributable component of the erosion, we re-run
# the same simulation using the **unadjusted** C and K factors — i.e. as
# if the catchment had not burned. Outputs land in a sibling
# ``Results_baseline/`` folder so they sit alongside, rather than
# overwriting, the fire-impacted results. Differencing the two gives
# the erosion uplift caused by the fire.

# %%
# The baseline uses the unadjusted C/K factors and the baseline SDR
# (SDR_baseline.tif). These are all produced during PrepareData by
# compute_adjusted_k_c, so no extra preparation is needed here — just build
# a fresh recorder set (recorders carry accumulator state from the fire run)
# and run with use_fire_adjusted=False.
baseline_recorders = recorder_factory(
    ctx, rain_seq.index[0], rain_seq.index[-1])
baseline_results = rusle.run_usle_simulation(
    ctx, rain_seq,
    recorders=baseline_recorders,
    use_fire_adjusted=False,
)

# %% [markdown]
# ### What produced these results?
#
# Every run records what it was built from, beside the outputs it wrote.
# Six months later — or when someone else opens the project — this is how
# you find out what a set of results actually means.

# %%
# One object covering the run's identity, the parameters it resolved, and
# the input layers it read.
prov = ctx.results_provenance()
print(prov.summary())

# %% [markdown]
# `chosen()` is usually the interesting half: the parameters somebody set,
# as opposed to the ones still on package defaults. An empty result means
# this run used the shipped calibration throughout.

# %%
prov.chosen()

# %% [markdown]
# `to_frame()` gives the whole resolved set, one row per parameter, with
# where each value came from — `default`, `project`, `catchment`, `event`
# or `call`. That distinction is the point: it tells a deliberate 0.5
# apart from a defaulted one.

# %%
prov.to_frame()

# %% [markdown]
# Two runs can be compared directly, because the frames are sorted.

# %%
# baseline = ctx.results_provenance('Results_baseline')
# prov.to_frame().compare(baseline.to_frame())

# %% [markdown]
# ### Where the inputs came from
#
# `inputs` maps each layer the run read to a digest of the parameters that
# built it. The simulation checks these before it runs and refuses to mix
# calibrations, so a mismatch is normally caught rather than discovered —
# but the digests are here if you want to confirm two runs read the same
# layers.

# %%
prov.inputs

# %% [markdown]
# The same information lives on each raster as GeoTIFF metadata, so a
# layer still answers for itself once it has been copied out of the
# project — `gdalinfo <file> | grep FIRE_IMPACTS` from a shell, or:

# %%
from fire_impacts.provenance import read_parameter_tags

read_parameter_tags(ctx.event_path('Delivery', 'SDR_t0.tif'))

# %% [markdown]
# If the fire severity was substituted rather than derived — a synthetic
# fire, a supplied raster, or a uniform value — that is recorded too,
# including the seed actually used, so the draw can be reproduced.

# %%
from fire_impacts.pre.materialise import read_binding_record

read_binding_record(ctx)   # None when dNBR came from the normal pipeline

# %% [markdown]
# ### Viewing RUSLE simulation results
#
# One easy, intuitive way to view the rsults is as a daily timeseries of total mass eroded each day. This is embedded within the `results` object created above

# %%
results['erosion_daily_time_series']

# %% [markdown]
# You can also visualise the various outputs.
# - To view the results for the whole catchment as a raster, use `plot_catchment_raster()`
#     - Grids are written to the `Results` folder, named by recorder key
#       (e.g. 'RUSLE_sum_total', 'delivered_max_total').
# - To view results aggregated by subcatchment, use `plot_subcatchments()`
#     - Pass the catchment name, `data_type='Results'`, and the recorder key.
#     - The data is aggregated per subcatchment using the appropriate stat:
#         - Sum for totals (e.g. 'RUSLE_sum_total', 'delivered_sum_total')
#         - Mean for peaks/max (e.g. 'RUSLE_max_total', 'delivered_max_total')
#
# Examples of the different visualisations for our example catchment are shown in the following cells.
#
# > The `plot_subcatchments()` cells need subcatchments registered by *PrepareData*, which it does when `catchment.subcatchments` is set in `study.toml`. Without them no subcatchment summary was written, and those cells stop with a message naming `add_subcatchments()` — skip them and read the whole-catchment rasters instead.

# %%
# To see a complete picture of sediment eroded across the catchment:
proj.plot_catchment_raster('Results', 'RUSLE_sum_total', ctx=ctx)

# %%
# To see the total sediment eroded across each subcatchment:
proj.plot_subcatchments(catchment=CATCHMENT, data_type='Results', colour_col='RUSLE_sum_total', ctx=ctx)

# %%
# To see the maximum erosion for any 30-minute period for each cell:
proj.plot_catchment_raster('Results', 'RUSLE_max_total', ctx=ctx)

# %%
# To see the average maximum erosion in any 30-minute period across subcatchments:
proj.plot_subcatchments(catchment=CATCHMENT, data_type='Results', colour_col='RUSLE_max_total', ctx=ctx)

# %% [markdown]
# Once we've predicted how much sediment has *eroded* from each cell, the final RUSLE step is to work out how much of that eroded sediment actually makes its way downhill and is *delivered* to the stream network.

# %%
# Total sediment delivered to streams over the simulation:
proj.plot_catchment_raster('Results', 'delivered_sum_total', ctx=ctx)

# %%
# Totals delivered from each subcatchment:
proj.plot_subcatchments(catchment=CATCHMENT, data_type='Results', colour_col='delivered_sum_total', ctx=ctx)

# %%
# Largest mass of sediment delivered during any 30-minute period for each cell:
proj.plot_catchment_raster('Results', 'delivered_max_total', ctx=ctx)

# %%
# Average maximum sediment delivered during any 30-minute period across each subcatchment:
proj.plot_subcatchments(catchment=CATCHMENT, data_type='Results', colour_col='delivered_max_total', ctx=ctx)

# %% [markdown]
# ## Debris Flow Simulation
#
# Debris flow operates on headwaters only and uses 12 minute rainfall _intensity_ data.
#
# The first thing we need to do is convert the rainfall *depth* values provided by pyraingen, to *intensity* values and then resample to 12-minute intervals
#

# %%
from fire_impacts.sim import convert_rainfall_depth_to_intensity

# %%
rainfall_intensity = convert_rainfall_depth_to_intensity(rainfall_data)
rainfall = aggregate_rainfall_data(rainfall_intensity,rain_data_start,rain_data_end,time_res='12min')
rainfall.rainfall

# %%
# Extract and inspect one replicate:
rain_intensity_seq = rainfall.rainfall[:, INSPECT_REPLICATE].to_pandas()
rain_intensity_seq
# %% [markdown]
# ### Stale layer check
#
# The C/K/SDR layers this run reads were built by PrepareData. If you have
# changed a preprocessing parameter since then, the simulation raises
# rather than silently mixing two calibrations — re-run
# `compute_adjusted_k_c`, or pass `allow_stale=True` if the mismatch is
# deliberate. Only the parameters a layer depends on are compared.

# %% [markdown]
# ### Run the simulation

# %%
df_results = debris_flow(ctx, rain_intensity_seq)

# %% [markdown]
# ### Viewing debris flow simulation results
#
# A table of results for each headwater will be saved to the project's **DebrisFlow** folder. If `catchment.subcatchments` is set, a separate table is also created with the same results aggregated to subcatchments; without it that step is skipped, and so are the `plot_subcatchments()` cells below.
#
# The easiest way to interpret the results is to use the build in visualisation methods: `plot_headwaters()` and `plot_subcatchments()`.
#
# > **Note**: For this example, and in many cases, rainfall intensity values might be below the threshold required to initiate a debris flow in any of the headwaters.

# %%
# To see the calculated critical thresholds for debris flow:
proj.plot_headwaters(CATCHMENT, 'I12_crit_mean_Year_1', data_type='DebrisFlow', ctx=ctx)

# %%
# The same, aggregated as the average threshold for each subcatchment:
proj.plot_subcatchments(CATCHMENT, 'DebrisFlow', 'I12_crit_mean_Year_1', ctx=ctx)

# %%
# To see the number of debris flow events in each headwater:
proj.plot_headwaters(CATCHMENT, 'Year1_num_events', data_type='DebrisFlow', ctx=ctx)

# %%
# And by subcatchment:
proj.plot_subcatchments(CATCHMENT, 'DebrisFlow', 'Year1_num_events', ctx=ctx)

# %%
# Finally we can view the mass that would form part of a debris flow in each subcatchment:
proj.plot_subcatchments(CATCHMENT, 'DebrisFlow', 'mass', ctx=ctx)

# %%
