# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.18.1
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Fire impacts simulations
#
# This notebook demonstrates the fire impacts simulation modules.
#
# It is assumed that you have a `FireImpactsProject` populated with all pre-processed data for the catchment.

# %%
import logging
logging.basicConfig(level=logging.INFO,format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

from fire_impacts.sim import aggregate_rainfall_data, lumped_daily_rusle, gridded_total_rusle, debris_flow
from fire_impacts import FireImpactsProject
from fire_impacts.context import RunContext

import matplotlib.pyplot as plt


# %%

# %% [markdown]
# ## Load project

# %%
proj = FireImpactsProject('/home/joelrahman/Geospatial/waterra-bushfire/example-project/',exist_ok=True)

# %%
proj.catchments

# %%

# %% [markdown]
# ## Rainfall data
#
# Both the erosion (RUSLE) and debris flow modules rely on subdaily rainfall data. The erosion modules, demonstrated here, relies on 30 minute data, while the debris flow relies on 12 minute data.
#
# Furthermore, it is encouraged that both modules be run stochastically, using multiple rainfall replicates.
#
# The library provides functionality for processing stochastic rainfall data, generated by [pyraingen](https://github.com/crdykman/pyraingen).
#
# We will initially run a short simulation of only three days.

# %%
rain_data_start = '2015-01-01'
rain_data_end = '2015-01-03'

# Pointer to pyraingen generated stochastic rainfall
rainfall_data = '/home/joelrahman/Geospatial/waterra-bushfire/rusle/subdaily_012345.nc'


# %%
# aggregate_rainfall_data?

# %%

# %%
rainfall_30min = aggregate_rainfall_data(rainfall_data,rain_data_start,rain_data_end)

# %%
rainfall_30min

# %% [markdown]
# **Note:** The pyraingen data includes 10 stochastic replicates. In the following examples, we will only use one replicate.
#

# %% [markdown]
# ## Erosion - Daily simulation
#
# Erosion processed are modelled cell-by-cell, timestep-by-timestep.
#
# This can result in a large amount of output that in most cases is not directly usable.
#
# The library currently provides two alternative function calls, depending on the nature of outputs required:
#
# * `lumped_daily_rusle`: For modelling erosion processes and receiving daily outputs lumped to the subcatchment scale, and
# * `gridded_total_rusle`: For modelling erosion processes and receiving gridded outputs summing the erosion over the simulation period.
#
# Both of these functions rely on a low level function which can be used to provide customise outputs
#

# %%

# %% [markdown]
# First, lets run the lumped daily function:

# %%
# lumped_daily_rusle?

# %%

# %%
# Build a run-level RunContext bound to a particular fire event and
# climate ensemble. solo_run resolves the catchment when the project has
# exactly one; otherwise pass catchment= explicitly.
ctx = RunContext.solo_run(
    proj, event='2019_fire', ensemble='historical',
    catchment='DR_Primary_Catchment_Thomson',
)

lumped_daily_rusle(ctx, rainfall_30min[9])

# %%

# %% [markdown]
# ## Erosion - Gridded simulation
#
# This time, we will run for a longer time period (2 years) and retrieve a single map of predicted erosion over this time period

# %%
rain_data_start = '2015-01-01'
rain_data_end = '2016-12-31'
rainfall_30min = aggregate_rainfall_data(rainfall_data,rain_data_start,rain_data_end)

# %%

# %%
# gridded_total_rusle?

# %%

# %%
# %time eroded, delivered, transform = gridded_total_rusle(proj,rainfall_30min[9],'DR_Primary_Catchment_Thomson')

# %%

# %%
plt.imshow(eroded)
plt.colorbar()

# %%

# %%
plt.imshow(delivered)
plt.colorbar()

# %%

# %% [markdown]
# ## Debris Flow
#
# Debris flow operates on headwaters only and uses 12 minute rainfall data.
#

# %%
rain_data_start = '2015-01-01'
rain_data_end = '2016-12-31'
rainfall = aggregate_rainfall_data(rainfall_data,rain_data_start,rain_data_end,time_res='12min')
rainfall

# %%
results = debris_flow(ctx, rainfall[9])

# %%

# %%
summary_df, event_ts = results
summary_df

# %%
