# warnings.deprecated was added in Python 3.13. Provide a compatible
# fallback for older environments that emits a DeprecationWarning.
try:
    from warnings import deprecated
except ImportError:
    import functools
    import warnings as _warnings

    def deprecated(msg):
        """Backport shim for warnings.deprecated (Python < 3.13)."""
        def decorator(func):
            @functools.wraps(func)
            def wrapper(*args, **kwargs):
                _warnings.warn(
                    f"{func.__name__} is deprecated: {msg}",
                    DeprecationWarning,
                    stacklevel=2,
                )
                return func(*args, **kwargs)
            return wrapper
        return decorator

from affine import Affine
import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio.mask import mask
from rasterio.warp import reproject, Resampling
import os
import logging
import time
from fire_impacts import const as c
from fire_impacts.const import M2_TO_HA, MILLIGRAMS_TO_KILOGRAMS
from fire_impacts.pre.util import read_aligned, read_raster
from fire_impacts.util import load_package_data, get_zonal_stats
logger = logging.getLogger(__name__)

from fire_impacts.pre import FireImpactsProject
from fire_impacts.pre.project import save_catchment_raster

DNBR_SEVERITY_THRESHOLD = 400
EMPIRICAL_COEFFICIENT = 0.082
LOG_INTERVAL_SECONDS = 15.0

###############################################################################
def compute_klscp_layer(
    proj:FireImpactsProject,
    catchment:str,
    support_practice_factor:float=1.0,
    use_fire_adjusted:bool=True
    ):
    """
    Using previously-generated C, K, and LS factor rasters, compute
    KLSCP values for the catchment in memory.

    When ``use_fire_adjusted=False`` the unadjusted C and K factors are
    used instead, producing a pre-fire baseline KLSCP for comparison
    against the fire-impacted result.

    Returns: (klscp_array, metadata_dict)
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    c_name = 'C_factor_adjusted.tif' if use_fire_adjusted else 'C_factor.tif'
    k_name = 'K_factor_adjusted.tif' if use_fire_adjusted else 'K_factor.tif'
    c_factor_path = proj.catchment_path(catchment, 'Erodibility', c_name)
    k_factor_path = proj.catchment_path(catchment, 'Erodibility', k_name)
    ls_factor_path = proj.catchment_path(
        catchment,
        'Erodibility',
        'LS_factor.tif'
        )

    # LS is always at DEM resolution. Align C and K to it — the
    # unadjusted rasters are stored at their native (coarse) source
    # resolution, so a direct read() would give mismatched shapes.
    with rasterio.open(ls_factor_path) as ls_factor:
        ls_array = ls_factor.read(1)
        meta = ls_factor.meta.copy()
        transform = meta['transform']
        crs = meta['crs']

    c_array = read_aligned(c_factor_path, transform, crs, ls_array.shape)
    k_array = read_aligned(k_factor_path, transform, crs, ls_array.shape)

    # Perform the multiplication for RUSLE base layer
    base = (c_array * k_array * ls_array * support_practice_factor).astype(np.float32)

    meta.update(dtype=rasterio.float32, count=1, compress='lzw')

    return base, meta

###############################################################################
def _rusle_parameter_grids(project:FireImpactsProject, catchment:str, use_fire_adjusted:bool=True):
    """
    Organise relevant raster parameters and return them as usable
    data objects ready for rusle calculations.

    Parameters:
    - project (FireImpactsProject object): The current project, which
    should already have the relevant rasters saved in its directories.
    - catchment (string): Name of the catchment to get the grids for.

    Returns:
    - The data ONLY (as an array), for KLSCP, SDR, and DNBR.
    - The cell area (in hectares) and the raster transform object,
    which should be usable by all three data arrays.
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    cell_area_m2 = project.cell_area(catchment)
    cell_area_ha = cell_area_m2 * M2_TO_HA  # Convert to hectares

    # Compute KLSCP layer in memory:
    klscp, klscp_meta = compute_klscp_layer(
        project, catchment, use_fire_adjusted=use_fire_adjusted
        )

    transform = klscp_meta['transform']
    crs = klscp_meta['crs']

    # Get the Sediment Delivery Ratio (SDR) raster, which is generated
    #ultimately by the calculate_lumped_rusle() function in this module:
    sdr,_ = read_raster(
        project.catchment_path(
            catchment,
            'Delivery',
            'SDR.tif'
            )
        )

    # Get the delta Normalised Burn Ratio (dNBR) raster, which is
    #generated by severity.calculate_fire_severity(). Use read_aligned
    #to ensure it's in the same CRS as the RUSLE layers.
    # Do we need to do this? Why don't we do it for SDR too?
    dnbr = read_aligned(
        project.catchment_path(
            catchment,
            'FireSeverity',
            'masked_dNBR.tif'
            ),
        transform,
        crs,
        klscp.shape
        )
    return klscp, sdr, dnbr, cell_area_ha, transform

###############################################################################
def lumped_daily_rusle(project:FireImpactsProject, rainfall, catchment=None):
    """
    Calculates RUSLE and SDR erosion values for sub-catchments based on 30min rainfall sequence.

    Parameters:
    - project (fire_impacts.FireImpactsProject): Current project
    - rainfall (Series-like): 30 minute rainfall data (mm)
    - catchment (str): Name of the catchment to process. If None, process all catchments.

    Returns:
    - RUSLE_df (DataFrame): DataFrame summarizing RUSLE and sediment delivery results.
    """
    if catchment is None:
        return project.for_each_catchment(lambda c: lumped_daily_rusle(project,rainfall,c))

    if 'units' not in rainfall.attrs:
        logger.warning("Rainfall data has no units attribute, assuming units are correct (mm)")
    elif rainfall.attrs['units'] != 'mm':
        logger.error("Rainfall data has units '%s', expected 'mm'", rainfall.attrs['units'])
        raise ValueError("Rainfall data has units '%s', expected 'mm'"%rainfall.attrs['units'])
    RUSLE_df = calculate_lumped_rusle(project.get_subcatchments(catchment), rainfall, *_rusle_parameter_grids(project,catchment))

    logger.info('Done')
    return RUSLE_df

###############################################################################
def record_summary_grid(variable,fn='sum',start_time=None,end_time=None):
    '''
    Build a RUSLE recorder that summarizes a grid variable over time.

    Parameters:
    - variable (str): Name of the variable to summarize.
    - fn (str): Summary function to use: 'sum', 'mean', 'max'. Default is 'sum'.
    - start_time (datetime): OPTIONAL: Start time for the summary. If None, use the start of the simulation.
    - end_time (datetime): OPTIONAL: End time for the summary. If None, use the end of the simulation.
    Returns:
    - grid_recorder (function): A recorder function that can be used in the simulation (see: run_usle_simulation).
    '''
    result = None
    count = 0
    def grid_recorder(timestep,**kwargs):
        nonlocal result, count
        count += 1
        if start_time is not None and timestep < start_time:
            return result
        if end_time is not None and timestep > end_time:
            return result

        data = kwargs[variable]
        if result is None:
            result = data
        elif fn=='max':
            result = np.maximum(result, data)
        else:  # sum or mean
            result += data
        if fn=='mean':
            return result / count

        return result

    def reset():
        nonlocal result, count
        result = None
        count = 0

    def finalize():
        nonlocal result, count
        if fn=='mean':
            return result / count
        return result
    grid_recorder.reset = reset
    grid_recorder.finalize = finalize

    return grid_recorder

###############################################################################
def record_subcatchment_timeseries(
    proj:FireImpactsProject,
    variable_name:str,
    fn="sum",
    label_field=None,
    agg_count=1
    ):
    """
    Build a RUSLE recorder that summarizes a variable over
    subcatchments

    Parameters:
    - proj (fire_impacts.FireImpactsProject): Current project
    - variable_name (str): Name of the variable to summarize.
    - fn (str): Summary function to use: 'sum', 'mean', 'max'. Default
    is 'sum'.
    - label_field (str): OPTIONAL: Field in the catchment boundaries to
    use as labels. If None, use the index.
    - agg_count (int): OPTIONAL: Number of timesteps to aggregate
    before recording. Default is 1

    Returns:
    - timeseries_recorder (function): A recorder function that can be
    used in the simulation (see: run_usle_simulation).
    --------------------------------------------------------------------
    Notes:
    - While the time series can always be resampled to a desired
    timestep AFTER the simulation, the agg_count parameter can be used
    to speed things up significantly by aggregating (sum) over multiple
    timesteps during the simulation itself.
    - agg_count would only be 1 if the value in the data was already in
    the desired time series interval i.e. if you were making a daily
    timeseries and had one 'row' per day in the data.
    --------------------------------------------------------------------
    """
    result = None
    index = None
    zones = None
    zone_names = None

    intermediate=None
    intermediate_count = 0
    ###########################################################################
    def timeseries_recorder(timestep,catchment,transform,**kwargs):
        """
        Primary closure function for building a timeseries of
        aggregated values.

        Parameters:
        - timestep:
        - catchment (str): Name of the catchment currently being worked
        with
        - transform: Rasterio transform object used for converting
        polygons to raster

        Returns:
        - None until the number of timesteps processed equals the
        requested number of aggregations, then a dictionary of arrays
        with one key:value pair for each zone.
        ----------------------------------------------------------------
        ----------------------------------------------------------------
        """
        # Declare the variables defined in the next function layer out
        #so this inner function will remember their values between
        #calls:
        # Row labels (index) and aggregated values (results) that will
        #be used to build the final dataframe:
        nonlocal result, index
        # The spatial zones, and their corresponding zone names, for
        #which aggregated values will be recorded in the timeseries.
        #Each zone will be a column in the final output with the zone
        #name as the column label:
        nonlocal zones, zone_names
        # intermediate will start as just the variable name, and then
        #it will be a string with a copy of the variable name for each
        #time this has been run (why?). intermediate_count is the
        #number of times this has happened.
        nonlocal intermediate, intermediate_count

        # kwargs here is a dictionary of some single values like 'total
        #rain' and 'erosivity', and some arrays for things like 'RUSLE'
        #and SDR.
        data = kwargs.get(variable_name)
        # Throw an error if variable name hasn't been provided:
        if data is None:
            raise ValueError(
                f"Variable {variable_name} not found in simulation data."
                )
        # If zones haven't been provided, we still need an area for
        #consistent behaviour:
        if zones is None:
            # Zone each subcatchment separately; fall back to the
            # catchment boundary as a single zone when no subcatchments
            # have been registered for the catchment.
            try:
                boundaries_v = proj.get_subcatchments(catchment)
            except FileNotFoundError:
                boundaries_v = proj.catchment_boundary(catchment)
            resolved_label = label_field
            if resolved_label is None:
                resolved_label = proj.subcatchment_label_field(catchment)
            # List method to build an array of rasters the same shape
            #as the catchment boundary:
            zones = [
                rasterio.features.rasterize(
                    [g], # The geometry (see 'for g in ...')
                    transform=transform,
                    fill=np.nan,
                    dtype=np.float32,
                    out_shape=data.shape
                    ) for g in boundaries_v.geometry
                ]
            if resolved_label is None:
                zone_names = boundaries_v.index.values
            elif resolved_label not in boundaries_v.columns:
                logger.warning(
                    "Subcatchment label field '%s' is configured for "
                    "catchment '%s' but is not present in the saved "
                    "subcatchments shapefile (columns: %s). Falling "
                    "back to integer indices. Re-run "
                    "FireImpactsProject.add_subcatchments(..., "
                    "label_field='%s') to rewrite the shapefile with "
                    "the label column retained.",
                    resolved_label, catchment,
                    list(boundaries_v.columns), resolved_label,
                )
                zone_names = boundaries_v.index.values
            else:
                zone_names = boundaries_v[resolved_label].values

        # Update the counter for the number of times this has been run:
        intermediate_count += 1
        if intermediate is None:
            intermediate = data
        else:
            # Data and intermediate are both arrays; intermediate is
            #the aggregation of all timesteps already recorded in the
            #current cycle, and data is the single values for the
            #new timestep currently being processed.
            # Note that these are 3D arrays, so when you add data to
            #intermediate it adds a new 2D array of the current set of
            #values, along the third dimension.
            intermediate += data

        # If we haven't yet reached the requested number of timesteps,
        #we haven't yet changed result so it will still be None.
        if intermediate_count < agg_count:
            return result
        # Once we've reached the requested agg count, store the whole
        #3D array as data and update intermediates to their starting
        #values.
        else:
            data = intermediate
            intermediate = None
            intermediate_count = 0
        # If there's not already an index specified, make an empty list
        #so we still have something to use:
        if index is None:
            index = []
        # Add the current timestep as the index value:
        index.append(timestep)

        # Make a copy of the set of arrays for each zone, where all the
        #values (cells) outside that zone will be NaN and those inside
        #will retain their values.
        masked = [data * zone for zone in zones]

        def agg(d):
            """
            Helper function to handle the requested aggregation
            """
            if fn == "sum":
                return np.nansum(d)
            elif fn == "mean":
                return np.nanmean(d)
            elif fn == "max":
                return np.nanmax(d)
            else:
                raise ValueError(f"Function {fn} not recognized.")

        # If there's not already a result, make a dictionary with a
        #list for every AoI:
        if result is None:
            result = {name: [] for name in zone_names}

        # For each zone-specific set of arrays, apply the requested
        #aggregation:
        grouped = [agg(d) for d in masked]
        # Using enumerate() on zone_names simply gives us an iterable
        #with a number for each zone name:
        for ix,name in enumerate(zone_names):
            # The key in result will be the zone name. The value will
            #be the array in grouped that is in the same position as
            #the current zone in zones.
            result[name].append(grouped[ix])

        return result

    ###########################################################################
    def reset():
        """
        Secondary closure function to revert all encapsulated variables
        to starting values.
        """
        # Access the encapsulated variables from the outer function:
        nonlocal result, index
        nonlocal zones, zone_names
        nonlocal intermediate, intermediate_count
        # Reset them all to their starting values:
        index = None
        zones = None
        zone_names = None
        result = None
        intermediate = None
        intermediate_count = 0

    ###########################################################################
    def finalize():
        """
        Secondary closure function
        """
        # Access the up-to-date result and index variables:
        nonlocal result, index
        # Go through each zone in the result dictionary and convert
        #the data to a numpy array (was it already one??)
        for key in result:
            result[key] = np.array(result[key])

        # Convert to a dataframe and return:
        return pd.DataFrame(result,index=index)

    # Add the two secondary closure functions as method-like
    #attachments to the main one
    timeseries_recorder.reset = reset
    timeseries_recorder.finalize = finalize
    return timeseries_recorder

###############################################################################
def record_grid_transform():
    t = None
    def get_transform(timestep,transform,**kwargs): ###,**kwargs):
        nonlocal t
        t = transform
        return t
    def r(): pass
    def f(): return t
    get_transform.reset = r
    get_transform.finalize = f

    return get_transform

###############################################################################
def aggregate_rusle_to_subcatchments(
    project: FireImpactsProject,
    catchment: str,
    results_section: str = c.RESULTS_FOLDER_NAME
    ) -> 'pd.DataFrame | None':
    """
    Compute zonal statistics for each saved RUSLE output raster and
    write a per-subcatchment summary CSV to the Results folder.

    Parameters:
    - project: FireImpactsProject managing the directory structure
    - catchment: name of the catchment to process

    Returns:
    - DataFrame with one row per subcatchment containing aggregated
      raster values, or None if no subcatchments are defined.
    -----------------------------------------------------------------------
    Notes:
    - 'Total' rasters (erosion_y1, erosion_y2, delivered_y1, etc.)
      are aggregated using SUM. Each cell value is total tonnes over
      the simulation period, so summing over a subcatchment gives
      the total tonnes for that subcatchment — physically sound.
    - 'Peak' rasters (peak_erosion_y1, etc.) are aggregated using
      MEAN. Each cell stores the highest 30-min erosion recorded at
      that cell, but peaks at different cells occur at different times.
      Summing them would imply all cells peaked simultaneously, which
      overstates the worst-case event load. Mean gives the average
      peak intensity per cell, characterising how erosion-prone the
      subcatchment is on its worst day.
    -----------------------------------------------------------------------
    """
    # Skip gracefully if subcatchments have not been set up yet:
    try:
        subcatch_gdf = project.get_subcatchments(catchment)
    except FileNotFoundError:
        logger.info(
            'No subcatchments defined for %s — skipping RUSLE '
            'subcatchment aggregation.',
            catchment
            )
        return None

    sc_id_col = project.subcatchment_id
    # Start the summary table with just the subcatchment ID:
    summary = subcatch_gdf[[sc_id_col]].copy().reset_index(drop=True)

    for raster_name in c.RUSLE_OUTPUT_RASTER_NAMES:
        raster_path = project.catchment_path(
            catchment,
            results_section,
            f'{raster_name}.tif'
            )
        if not os.path.exists(raster_path):
            continue

        # Choose aggregation stat based on raster type (see Notes):
        stat = 'mean' if 'peak' in raster_name else 'sum'

        zstats = get_zonal_stats(
            subcatch_gdf, raster_path, raster_name, stats=[stat]
            )
        # Column name makes the aggregation method explicit:
        col_name = f'{raster_name}_{stat}'
        summary[col_name] = [s[stat] for s in zstats]

    out_path = project.catchment_path(
        catchment,
        results_section,
        c.RUSLE_SC_SUMMARY_NAME + '.csv'
        )
    summary.to_csv(out_path, index=False)
    logger.info('Saved RUSLE subcatchment summary to %s', out_path)

    return summary


###############################################################################
def run_usle_simulation(
    project:FireImpactsProject,
    rainfall,
    catchment=None,
    recorders=None,
    save_rasters:bool=True,
    save_timeseries:bool=True,
    use_fire_adjusted:bool=True,
    results_section:str=None
    ):
    """
    Run the USLE simulation for a given project and rainfall data,
    recording results as specified.

    Parameters:
    - project (fire_impacts.FireImpactsProject): Current project
    - rainfall (Series-like): 30 minute rainfall data (mm)
    - catchment (str): Name of the catchment to process. If None,
    process all catchments.
    - recorders (dict): OPTIONAL: Dictionary of recorder functions to
    use during the simulation.
    - save_rasters (bool): Whether the output rasters should be saved 
    as GeoTIFF files to the results folder for the current catchment
    - save_timeseries (bool): Whether the daily timeseries should be 
    saved as a csv file to the results folder for the current catchment

    Returns:
    - results (dict): Dictionary of recorded results from the
    simulation.
    - params (tuple): Tuple of parameters used in the simulation
    (klscp, sdr, dnbr, cell_area_ha, transform).
    --------------------------------------------------------------------
    Notes:
    - Each recorder function should accept parameters
    (timestep, **data) and return recorded results.
    - The data dictionary passed to each recorder will contain keys
    such as 'RUSLE', 'delivered', etc.
    - Each recorder function should also have 'reset' and 'finalize'
    methods to manage state.
    --------------------------------------------------------------------
    """
    if catchment is None:
        return project.for_each_catchment(
            lambda ctmt: run_usle_simulation(
                project, rainfall, ctmt, recorders,
                save_rasters, save_timeseries,
                use_fire_adjusted=use_fire_adjusted,
                results_section=results_section,
                )
            )
    # Resolve the section where outputs will be written. Baseline runs
    # go to a sibling folder so they don't overwrite the fire-impacted
    # results produced alongside them.
    if results_section is None:
        results_section = (
            c.RESULTS_FOLDER_NAME if use_fire_adjusted
            else c.RESULTS_BASELINE_FOLDER_NAME
            )
    # If no recorders were passed, use an empty dictionary so the rest
    #of the code works consistently:
    if recorders is None:
        recorders = dict()
    # Reset each recorder so we're building new arrays for aggregation:
    for recorder in recorders.values():
        recorder.reset()

    # Get the relevant RUSLE parameters as handy arrays:
    params = _rusle_parameter_grids(project, catchment, use_fire_adjusted=use_fire_adjusted)
    klscp, sdr, dnbr, cell_area_ha, transform = params
    # Get the catchment boundary geometry in a form that's usable by
    #rasterio:
    catchment_boundary = project.catchment_boundary(catchment)
    # catchment_boundary = project.get_subcatchments(catchment).dissolve()
    geometry = catchment_boundary.geometry.values

    # Convert the catchment boundary to a raster with 1 for every cell
    #that's within the catchment boundary, and NaN for all others:
    mask = rasterio.features.rasterize(
        geometry,
        transform=transform,
        fill=np.nan,
        dtype=np.float32,
        out_shape=klscp.shape
        )

    # Use the mask to convert all values in the RUSLE grids that are
    #outside the catchment boundary to NaN:
    klscp_masked = klscp*mask
    sdr_masked = sdr*mask
    dnbr_masked = dnbr*mask

    # Empty dictionary to start filling with results:
    results = dict()
    # Iterate over each tuple of (timestep, values dict) produces by
    #the generate_rusle() generator function:
    for ts_data in generate_rusle(
        rainfall,
        klscp_masked,
        sdr_masked,
        dnbr_masked,
        cell_area_ha
        ):
        # Unpack the tuple elements:
        timestep, data = ts_data
        # Go through each encapsulating recorder function and load
        #the rusle data in for the current tuple:
        for key, recorder in recorders.items():
            results[key] = recorder(
                timestep,
                **data, # Unpack all values in the data dictionary
                catchment=catchment,
                transform=transform # from _rusle_parameter_grids() above
                )

    # Now that we've gone through all timesteps in the rainfall data,
    #get the final result. In the case of catchment timeseries, this
    #is a dataframe of the values aggregated for each of the specified
    #number of timesteps (48 for daily aggregation on half-hourly data).
    for key, recorder in recorders.items():
        results[key] = recorder.finalize()
    
    if save_rasters or save_timeseries:
        # Baseline runs land in a non-standard folder that the project
        # template doesn't pre-create. Make sure it exists.
        os.makedirs(
            project.catchment_path(catchment, results_section),
            exist_ok=True,
            )

    if save_rasters:
        template_raster = project.catchment_path(
            catchment,
            'Erodibility',
            'LS_factor.tif'
            )
        _, template_meta = read_raster(template_raster)
        for output_raster in c.RUSLE_OUTPUT_RASTER_NAMES:
            save_data = results.get(output_raster)
            if save_data is None:
                continue
            save_catchment_raster(
                project=project,
                catchment_name=catchment,
                file_name=output_raster,
                section=results_section,
                data=save_data,
                meta=template_meta
                )

        # Aggregate the saved rasters to subcatchments and write a
        # summary CSV alongside them (skipped if no subcatchments exist):
        aggregate_rusle_to_subcatchments(
            project, catchment, results_section=results_section
            )

    if save_timeseries:
        out_name = project.catchment_path(
            catchment,
            results_section,
            c.RUSLE_OP_TIMESERIES_NAME + '.csv'
            )
        output = pd.DataFrame(data=results[c.RUSLE_OP_TIMESERIES_NAME])
        output.index.name = 'Datetime'
        output.to_csv(out_name)

    # Attach a pointer to all the rusle parameters (mostly grids) used
    #for these calcs:
    results['params'] = params

    return results

###############################################################################
@deprecated("This function is deprecated and will be removed in a future version. Please use run_usle_simulation() with appropriate recorders instead.")
def gridded_total_rusle(project:FireImpactsProject, rainfall, catchment=None):
    """
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    if catchment is None:
        return project.for_each_catchment(lambda c: lumped_daily_rusle(project,rainfall,c))
    result = None
    # Get an iterable of the boundaries of each subcatchment in the
    #project:
    subcatch_boundaries = project.get_subcatchments(catchment).iloc[0].geometry

    total_eroded = None
    total_delivered = None
    params = _rusle_parameter_grids(project,catchment)
    for day_data in generate_rusle_for_feature([subcatch_boundaries], rainfall, *params):
        day, _, _, _, \
        daily_RUSLE, daily_SDR, \
        _, _, _, _ = day_data
        # logger.info('Processing day %s',day)
        if total_eroded is None:
            total_eroded = daily_RUSLE
            total_delivered = daily_SDR
        else:
            total_eroded += daily_RUSLE
            total_delivered += daily_SDR

    logger.info('Done')
    return total_eroded, total_delivered, params[-1]

###############################################################################
@deprecated("This function is deprecated and will be removed in a future version. Please use run_usle_simulation() with appropriate recorders instead.")
def calculate_lumped_rusle(
    subcatchments:gpd.GeoDataFrame,
    rainfall:pd.DataFrame,
    klscp:np.array,
    sdr:np.array,
    dnbr:np.array,
    cell_area_ha:float,
    transform:Affine
    ):
    """
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    daily_erosion = []
    # Read catchment shapefile
    # Loop through each catchment
    for ind, subcatchment in subcatchments.iterrows():
        logger.info('Processing subcatchment %d',ind+1)
        #catchment_name = catchment['PRIMARY_CA']  # Replace 'PRIMARY_CA' with the appropriate field for catchment names
        geometry = [subcatchment['geometry']]

        for day_data in generate_rusle_for_feature(geometry, rainfall, klscp, sdr, dnbr, cell_area_ha, transform):
            day, daily_total_rain, max_intensity, max_erosivity, \
            daily_RUSLE, daily_SDR, \
            daily_RUSLE_below_threshold, daily_RUSLE_above_threshold, \
            daily_SDR_below_threshold, daily_SDR_above_threshold = day_data

            # Store the daily result in the dictionary
            daily_erosion.append({
                'Sub-catchment': f"Sub_{ind+1}",
                # 'Simulation': sim.item()+1,
                'Day': day,
                'Rainfall (total daily)': daily_total_rain,
                'Max Rain Intensity (30 mins)': max_intensity,
                'Max Erosivity (30 mins)': max_erosivity,
                'RUSLE': np.nansum(daily_RUSLE),
                'RUSLE_SDR': np.nansum(daily_SDR),
                'RUSLE (Low severity)': np.nansum(daily_RUSLE_below_threshold),
                'RUSLE (High severity)': np.nansum(daily_RUSLE_above_threshold),
                'RUSLE_SDR (Low severity)': np.nansum(daily_SDR_below_threshold),
                'RUSLE_SDR (High severity)': np.nansum(daily_SDR_above_threshold),
            })
        #-------For some reason this code was docstrung previously:-----
        # Save the output raster
        # rusle_path = os.path.join(output_path, f"{catchment_name}_RUSLE_sim{sim.item()}_{day.item()}.tif")
        # with rasterio.open(rusle_path, 'w', **profile) as dst:
        #     dst.write(daily_RUSLE, 1)

        # sdr_rusle_path = os.path.join(output_path, f"{catchment_name}_SDR_RUSLE_sim{sim.item()}_{day.item()}.tif")
        # with rasterio.open(sdr_rusle_path, 'w', **profile) as dst:
        #     dst.write(daily_SDR_RUSLE, 1)
        #---------------------------------------------------------------

    # Convert the results to a DataFrame for analysis or saving
    RUSLE_df = pd.DataFrame(daily_erosion)
    # Read constituent data and convert it to ratio (its in mg per kg)
    # constituent_df = pd.read_csv(Constituent_path)
    RUSLE_df = compute_particulates(RUSLE_df)

    # Save to a CSV file if needed
    RUSLE_df=RUSLE_df.round(1)
    logger.info('Done')
    return RUSLE_df

###############################################################################
def generate_rusle(
    rainfall:pd.Series,
    klscp:np.array,
    sdr:np.array,
    dnbr:np.array,
    cell_area_ha:float
    ):
    """
    Generator function that produces an iterable of (timestep, dict)
    tuples for each timestep entry in the provided rainfall data. Dict
    is a lookup of all relevant RUSLE results for that timestep.

    Parameters:
    - rainfall (pd.Series like): Series with 30-minute rainfall data.
    Must be DEPTH values in mm.
    - klscp (np.array): Raster layer with KLSCP values.
    - sdr (np.array): Raster layer with SDR values.
    - dnbr (np.array): Raster layer with dNBR values.
    - cell_area_ha (float): Area of each cell in hectares.

    Yields:
    - Tuple with timestep and dict with results like
    (timestep (datetime), dict with keys)
    - Dictionary has the following keys and value types:
        - 'total_rain' (float)
        - 'intensity' (float)
        - 'erosivity' (float)
        - 'RUSLE' (np.array)
        - 'delivered' (np.array): sediment delivered to streams
          (RUSLE × SDR ratio), same units as RUSLE
        - 'RUSLE_below_threshold' (np.array)
        - 'RUSLE_above_threshold' (np.array)
        - 'delivered_below_threshold' (np.array)
        - 'delivered_above_threshold' (np.array))
    --------------------------------------------------------------------
    Notes:
    - This is a GENERATOR function which will return results as an
    iterable rather than one big dataset. Suits the use of recorders.
    - klscp, sdr and dnbr should have the same shape and transformation.
    --------------------------------------------------------------------
    """
    # Convert to Series if we've got a dataframe, to ensure consistency:
    if isinstance(rainfall, pd.DataFrame):
        rainfall = pd.Series(data=rainfall['rainfall'], index=rainfall.index)
    # Pre-compute severity masks based on dNBR thresholds
    dnbr_below_threshold = dnbr < DNBR_SEVERITY_THRESHOLD
    dnbr_above_threshold = dnbr >= DNBR_SEVERITY_THRESHOLD

    # Initialize timing variables for progress logging
    total_timesteps = len(rainfall.index)
    start_time = time.time()
    last_log_time = start_time
    iteration_count = 0

    # Loop over each 30-min timestep
    for timestep in rainfall.index:
        iteration_count += 1
        # Get rainfall amount (∆V_r) during the 30-min period
        delta_v_r = rainfall[timestep]

        # Initialize result dict
        result = {
            'total_rain': delta_v_r,
            'intensity': 0.0,
            'erosivity': 0.0,
            'RUSLE': np.zeros_like(klscp, dtype=np.float32),
            'delivered': np.zeros_like(klscp, dtype=np.float32),
            'RUSLE_below_threshold': np.zeros_like(klscp, dtype=np.float32),
            'RUSLE_above_threshold': np.zeros_like(klscp, dtype=np.float32),
            'delivered_below_threshold': np.zeros_like(klscp, dtype=np.float32),
            'delivered_above_threshold': np.zeros_like(klscp, dtype=np.float32),
        }

        # Skip calculations if delta_v_r is 0
        if delta_v_r == 0:
            yield (timestep, result)
            continue

        # Calculate rainfall intensity (∆V_r / ∆t_r)
        intensity = delta_v_r / 0.5  # mm/hr
        result['intensity'] = intensity

        # Calculate unit kinetic energy (e_r)
        e_r = 0.29 * (1 - 0.72 * np.exp(-EMPIRICAL_COEFFICIENT * intensity))

        # Calculate energy (E)
        E = e_r * delta_v_r

        # Calculate erosivity factor (R)
        R = E * intensity
        result['erosivity'] = R

        # Calculate RUSLE
        # TODO: sediment eroded? kg? t?
        RUSLE = (R * klscp) * cell_area_ha  # Total erosion in tonnes per hectare
        result['RUSLE'] = RUSLE

        # Sediment delivered to streams: erosion × SDR ratio.
        # TODO: confirm units (tonnes?)
        delivered = RUSLE * sdr
        result['delivered'] = delivered

        # Apply severity masks
        result['RUSLE_below_threshold'] = np.where(dnbr_below_threshold, RUSLE, 0)
        result['RUSLE_above_threshold'] = np.where(dnbr_above_threshold, RUSLE, 0)
        result['delivered_below_threshold'] = np.where(dnbr_below_threshold, delivered, 0)
        result['delivered_above_threshold'] = np.where(dnbr_above_threshold, delivered, 0)

        # Check if LOG_INTERVAL_SECONDS have elapsed since last log
        current_time = time.time()
        if current_time - last_log_time >= LOG_INTERVAL_SECONDS:
            progress_pct = (iteration_count / total_timesteps) * 100
            elapsed_time = current_time - start_time
            avg_time_per_iteration = elapsed_time / iteration_count
            remaining_iterations = total_timesteps - iteration_count
            estimated_time_remaining = avg_time_per_iteration * remaining_iterations

            # Format time remaining as hours:minutes:seconds
            hours, remainder = divmod(int(estimated_time_remaining), 3600)
            minutes, seconds = divmod(remainder, 60)
            time_str = f"{hours:02d}:{minutes:02d}:{seconds:02d}" if hours > 0 else f"{minutes:02d}:{seconds:02d}"

            logger.info(
                f"Progress: {iteration_count}/{total_timesteps} timesteps "
                f"({progress_pct:.1f}%) - Current timestep: {timestep} - "
                f"Estimated time remaining: {time_str}"
            )
            last_log_time = current_time

        yield (timestep, result)

@deprecated("This function is deprecated and will be removed in a future version. Please use run_usle_simulation() with appropriate recorders instead.")
def generate_rusle_for_feature(geometry:list, rainfall:pd.DataFrame, klscp:np.array, sdr:np.array, dnbr:np.array, cell_area_ha:float, transform:Affine):
    '''
    Calculates RUSLE and SDR erosion values for sub-catchments based on rainfall simulations.

    Parameters:
    - geometry (list): List of shapely geometries representing the sub-catchment.
    - rainfall (pd.Series like): Series with 30-minute rainfall data.
    - klscp (np.array): Raster layer with KLSCP values.
    - sdr (np.array): Raster layer with SDR values.
    - dnbr (np.array): Raster layer with dNBR values.
    - cell_area_ha (float): Area of each cell in hectares.
    - transform (Affine): Affine transformation for the raster layers.

    klscp, sdr and dnbr should have the same shape and transformation.

    Yield:
    - Tuple with daily results for the sub-catchment:
      day (datetime), daily_total_rain (float), max_intensity (float), max_erosivity (float),
      daily_RUSLE (np.array), daily_SDR (np.array),
      daily_RUSLE_below_threshold (np.array), daily_RUSLE_above_threshold (np.array),
      daily_SDR_below_threshold (np.array), daily_SDR_above_threshold (np.array)
    '''
    mask = rasterio.features.rasterize(geometry, transform=transform, fill=np.nan, dtype=np.float32, out_shape=klscp.shape)
    klscp_masked = klscp*mask
    sdr_masked = sdr*mask
    dnbr_masked = dnbr*mask

    days = pd.Series(rainfall.index.date).drop_duplicates()
    for day in days:
        rainfall_data = rainfall[rainfall.index.date==day]
        # Initialize daily arrays for RUSLE and SDR_RUSLE
        daily_RUSLE = np.zeros_like(klscp_masked, dtype=np.float32)
        daily_SDR = np.zeros_like(klscp_masked, dtype=np.float32)
        daily_total_rain = 0.0
        max_intensity = 0.0
        max_erosivity = 0.0

        # Loop over each 30-min interval
        for subday in rainfall_data.values:
            # Get rainfall amount (∆V_r) during the 30-min period
            # delta_v_r = rainfall_data.sel(subday_30mins=subday).values
            delta_v_r = subday
            daily_total_rain+=delta_v_r

            # Skip calculations if delta_v_r is 0
            if delta_v_r == 0: # What if spatial? max?
                continue

            # Calculate rainfall intensity (∆V_r / ∆t_r)
            intensity = delta_v_r / 0.5  # mm/hr
            max_intensity = max(max_intensity,intensity)

            # Calculate unit kinetic energy (e_r)
            e_r = 0.29 * (1 - 0.72 * np.exp(-EMPIRICAL_COEFFICIENT * intensity))

            # Calculate energy (E)
            E = e_r * delta_v_r

            # Calculate erosivity factor (R)
            R = E * intensity
            max_erosivity = max(max_erosivity,R)

            # Calculate RUSLE
            # TODO: sediment eroded? kg? t?
            RUSLE = (R * klscp_masked) * cell_area_ha # Total erosion in tonnes per hectare
            daily_RUSLE += RUSLE  # Accumulate RUSLE for the day

            # Calculate SDR_RUSLE
            # TODO: sediment delivered? kg? t?
            SDR_RUSLE = RUSLE * sdr_masked  # Delivered erosion/sediment
            daily_SDR += SDR_RUSLE  # Accumulate SDR_RUSLE for the day


        # Mask daily_RUSLE and daily_SDR_RUSLE for dNBR values
        dnbr_below_threshold = dnbr_masked < DNBR_SEVERITY_THRESHOLD
        dnbr_above_threshold = dnbr_masked >= DNBR_SEVERITY_THRESHOLD

        daily_RUSLE_below_threshold = np.where(dnbr_below_threshold, daily_RUSLE, 0)
        daily_RUSLE_above_threshold = np.where(dnbr_above_threshold, daily_RUSLE, 0)

        daily_SDR_below_threshold = np.where(dnbr_below_threshold, daily_SDR, 0)
        daily_SDR_above_threshold = np.where(dnbr_above_threshold, daily_SDR, 0)

        yield((day,daily_total_rain,max_intensity,max_erosivity,daily_RUSLE,daily_SDR,daily_RUSLE_below_threshold,daily_RUSLE_above_threshold,daily_SDR_below_threshold,daily_SDR_above_threshold))

def compute_particulates(rusle_df,constituents_df=None):
    if constituents_df is None:
        constituents_df = load_package_data('ash_constituents.csv')

    # Iterate through each constituent and severity
    for _, row in constituents_df.iterrows():
        particulate = row['Particulate constituent (ash)']
        low_severity = row['Low severity- mean amount (mgkg-1)'] * MILLIGRAMS_TO_KILOGRAMS
        high_severity = row['High severity- mean amount (mgkg-1)'] * MILLIGRAMS_TO_KILOGRAMS

        # Define new column name
        column_name = f"{particulate} (Tonne)"
        rusle_df[column_name] = (rusle_df['RUSLE_SDR (Low severity)'] * low_severity) + (rusle_df['RUSLE_SDR (High severity)'] * high_severity)
    return rusle_df

# ----- Functions for running RUSLE simulations for rainfall replicates in parallel with Dask -----
def run_rusle_replicate(
    proj,
    rainfall_30min,
    replicate_idx,
    recorder_factory=None,
    use_fire_adjusted=True,
):
    """Run the RUSLE simulation for a single rainfall replicate.

    Parameters
    ----------
    proj : FireImpactsProject
        Current project.
    rainfall_30min : xarray.Dataset
        Rainfall replicates dataset with a ``replicate`` dimension.
    replicate_idx : int
        Index of the replicate to run.
    recorder_factory : callable or None
        A factory ``(project, start, end) -> dict`` of recorders, as
        returned by :func:`default_rusle_recorders`.  When *None*, a
        default factory is created via ``default_rusle_recorders()``.

    Returns
    -------
    dict
        Keyed by catchment name, values are the recorder results dict
        for that catchment.
    """
    rain_seq = rainfall_30min.rainfall[:, replicate_idx].to_pandas()

    if recorder_factory is None:
        recorder_factory = default_rusle_recorders()

    start = rain_seq.index[0]
    end = rain_seq.index[-1]

    replicate_results = {}
    for c_name in proj.catchments:
        recorders = recorder_factory(proj, start, end)
        replicate_results[c_name] = run_usle_simulation(
            proj,
            rain_seq,
            catchment=c_name,
            recorders=recorders,
            save_rasters=False,
            save_timeseries=False,
            use_fire_adjusted=use_fire_adjusted,
        )

    return replicate_results


def run_rusle_all_replicates(
    proj,
    rainfall_30min,
    n_workers=None,
    scheduler='threads',
    replicate_indices=None,
    recorder_factory=None,
    use_fire_adjusted=True,
):
    """Run RUSLE simulations for selected rainfall replicates in parallel with Dask.

    Parameters
    ----------
    proj : FireImpactsProject
        Current project.
    rainfall_30min : xarray.Dataset
        Rainfall replicates dataset with a ``replicate`` dimension.
    n_workers : int or None
        Number of dask workers.
    scheduler : str
        Dask scheduler name (e.g. ``'threads'`` or ``'processes'``).
    replicate_indices : iterable of int or None
        Which replicates to run.  Default: all.
    recorder_factory : callable or None
        A factory ``(project, start, end) -> dict`` as returned by
        :func:`default_rusle_recorders`.  When *None*, a default factory
        is created via ``default_rusle_recorders()``.

    Returns
    -------
    dict
        Mapping replicate index (int) to simulation outputs.

    Examples
    --------
    Run all replicates with percentile timeseries (lighter output)::

        factory = default_rusle_recorders(timeseries_mode='percentiles')
        results = run_rusle_all_replicates(
            proj, rainfall, recorder_factory=factory
        )
    """
    import dask

    if recorder_factory is None:
        recorder_factory = default_rusle_recorders()

    if replicate_indices is None:
        replicate_indices = list(range(rainfall_30min.dims['replicate']))
    else:
        replicate_indices = list(replicate_indices)

    tasks = [
        dask.delayed(run_rusle_replicate)(
            proj,
            rainfall_30min,
            i,
            recorder_factory=recorder_factory,
            use_fire_adjusted=use_fire_adjusted,
        )
        for i in replicate_indices
    ]

    computed = dask.compute(*tasks, scheduler=scheduler, num_workers=n_workers)
    return {i: result for i, result in zip(replicate_indices, computed)}



###############################################################################
_PERIOD_OFFSETS = {
    'yearly': pd.DateOffset(years=1),
    'monthly': pd.DateOffset(months=1),
}


def _compute_periods(start, end, timestep_type):
    """Compute non-overlapping time period boundaries.

    Parameters
    ----------
    start, end : pd.Timestamp
    timestep_type : str
        ``'total'``, ``'yearly'``, or ``'monthly'``.

    Returns
    -------
    list of (period_start, period_end) tuples.  For non-final periods
    ``period_end`` is offset by -1 s so that the boundary timestep is
    not double-counted.
    """
    if timestep_type == 'total':
        return [(start, end)]

    offset = _PERIOD_OFFSETS.get(timestep_type)
    if offset is None:
        raise ValueError(
            f"Unsupported grid_timestep '{timestep_type}'. "
            "Use 'total', 'yearly', or 'monthly'."
        )

    periods = []
    period_start = start
    while period_start < end:
        period_end = period_start + offset
        if period_end > end:
            period_end = end
        periods.append((period_start, period_end))
        period_start = period_end

    # Offset non-final period ends by 1 s to avoid double-counting
    return [
        (ps, pe - pd.Timedelta(seconds=1)) if i < len(periods) - 1 else (ps, pe)
        for i, (ps, pe) in enumerate(periods)
    ]


###############################################################################
def record_multi_period_grid(variable, fn, periods):
    """Build a recorder that accumulates a summary grid per time period.

    Always returns an ``xarray.DataArray`` with georeferenced
    ``easting`` and ``northing`` coordinates (derived from the affine
    transform passed at each timestep).  Single-period results are 2-D
    ``(northing, easting)``; multi-period results are 3-D
    ``(time, northing, easting)``.

    Parameters
    ----------
    variable : str
        Key to extract from the per-timestep data dict.
    fn : str
        ``'sum'``, ``'max'``, or ``'mean'``.
    periods : list of (start, end) tuples
        Each pair is a ``(pd.Timestamp, pd.Timestamp)`` half-open interval.
    """
    # Accumulators — one entry per period
    grids = [None] * len(periods)
    counts = [0] * len(periods)
    captured_transform = [None]  # mutable container for nonlocal capture

    def recorder(timestep, **kwargs):
        data = kwargs[variable]
        if captured_transform[0] is None and 'transform' in kwargs:
            captured_transform[0] = kwargs['transform']
        for i, (ps, pe) in enumerate(periods):
            if timestep < ps or timestep > pe:
                continue
            counts[i] += 1
            if grids[i] is None:
                grids[i] = data.copy()
            elif fn == 'max':
                np.maximum(grids[i], data, out=grids[i])
            else:
                grids[i] += data

    def reset():
        for i in range(len(periods)):
            grids[i] = None
            counts[i] = 0
        captured_transform[0] = None

    def _build_spatial_coords(shape):
        """Build easting/northing coordinate arrays from the transform."""
        t = captured_transform[0]
        if t is None:
            return {}
        rows, cols = shape
        easting = np.array([t.c + (col + 0.5) * t.a for col in range(cols)])
        northing = np.array([t.f + (row + 0.5) * t.e for row in range(rows)])
        return {'easting': easting, 'northing': northing}

    def finalize():
        import xarray as xr

        # Determine grid shape from the first non-None accumulator
        shape = None
        for g in grids:
            if g is not None:
                shape = g.shape
                break
        if shape is None:
            return None

        arrays = []
        for i in range(len(periods)):
            g = grids[i]
            if g is None:
                g = np.zeros(shape, dtype=np.float32)
            elif fn == 'mean' and counts[i] > 0:
                g = g / counts[i]
            arrays.append(g)

        spatial = _build_spatial_coords(shape)

        if len(arrays) == 1:
            return xr.DataArray(
                arrays[0],
                dims=['northing', 'easting'],
                coords=spatial,
            )

        time_coords = [ps for ps, _ in periods]
        stacked = np.stack(arrays, axis=0)
        coords = {'time': time_coords, **spatial}
        return xr.DataArray(
            stacked,
            dims=['time', 'northing', 'easting'],
            coords=coords,
        )

    recorder.reset = reset
    recorder.finalize = finalize
    return recorder


###############################################################################
# Model timestep used to convert timeseries_timestep to an agg_count
_MODEL_TIMESTEP = pd.Timedelta(minutes=30)


def default_rusle_recorders(
    include_grids=True,
    grid_variables=('RUSLE',),
    grid_fns=('sum', 'max'),
    grid_timesteps=('yearly',),
    include_timeseries=True,
    timeseries_variables=('RUSLE',),
    timeseries_fn='sum',
    timeseries_timestep='24h',
    timeseries_label_field=None,
    timeseries_mode='full',
    include_transform=True,
):
    """Configure RUSLE output recorders and return a factory function.

    The returned factory creates a fresh dictionary of recorder closures
    each time it is called, so every simulation run (or dask task) gets
    independent state.  Because the configuration closure captures only
    plain Python values (no project object), it is trivially serializable
    for dask.

    The grid recorders are built from the cartesian product of
    ``grid_variables × grid_fns × grid_timesteps``.  Each combination
    produces one entry in the recorder dict, keyed as
    ``'{variable}_{fn}_{timestep}'`` (e.g. ``'RUSLE_sum_yearly'``).

    All grid results are ``xarray.DataArray`` objects with georeferenced
    ``easting`` and ``northing`` coordinates.  Multi-period results
    (e.g. yearly over a 2-year simulation) have an additional ``time``
    dimension.  Single-period results (e.g. ``'total'``) are 2-D.

    Parameters
    ----------
    include_grids : bool
        Whether to include grid summary recorders.  Default ``True``.
        When ``False``, ``grid_variables``, ``grid_fns``, and
        ``grid_timesteps`` are ignored.
    grid_variables : tuple of str
        Variables from the RUSLE generator to record in summary grids.
        Default ``('RUSLE',)``.
    grid_fns : tuple of str
        Summary functions to apply per period.  Supported: ``'sum'``,
        ``'max'``, ``'mean'``.  Default ``('sum', 'max')``.
    grid_timesteps : tuple of str
        Temporal aggregation levels.  Supported: ``'total'``, ``'yearly'``,
        ``'monthly'``.  Default ``('yearly',)``.
    include_timeseries : bool
        Whether to include subcatchment timeseries recorders.  Default
        ``True``.  When ``False``, all ``timeseries_*`` parameters are
        ignored.
    timeseries_variables : tuple of str
        Variables to record as subcatchment timeseries.  One recorder is
        created per variable.  Default ``('RUSLE',)``.
    timeseries_fn : str
        Spatial aggregation function for the timeseries.  Default ``'sum'``.
    timeseries_timestep : str or pd.Timedelta
        Output timestep for timeseries rows, e.g. ``'24h'``, ``'1h'``,
        ``'12h'``.  Converted to an aggregation count based on the 30-min
        model timestep.  Default ``'24h'`` (daily).
    timeseries_label_field : str or None
        Column in the subcatchment boundaries to use as zone labels.
    timeseries_mode : str
        ``'full'`` returns the complete DataFrame; ``'percentiles'``
        finalizes to a DataFrame of 101 percentiles (0–100) per
        subcatchment, suitable for exceedance probability plots and
        much lighter than the full timeseries for ensemble runs;
        ``'none'`` skips the timeseries entirely (equivalent to
        ``include_timeseries=False``).
    include_transform : bool
        Whether to include the ``record_grid_transform`` recorder.

    Returns
    -------
    factory : callable
        ``factory(project, start, end) -> dict`` of recorder callables
        ready for :func:`run_usle_simulation`.  *project* is a
        ``FireImpactsProject`` (needed only when timeseries recorders are
        included).  *start* and *end* can be any type accepted by
        ``pd.Timestamp`` (string, datetime, Timestamp).  Period boundaries
        are computed automatically from the simulation period.

    Examples
    --------
    Default usage (yearly sum + max grids for RUSLE, daily timeseries)::

        make_recorders = default_rusle_recorders()
        recorders = make_recorders(proj, '2020-01-01', '2021-12-31')
        results = run_usle_simulation(proj, rain, 'MyCatchment',
                                      recorders=recorders)

    Multiple variables, monthly + total grids, hourly timeseries::

        make_recorders = default_rusle_recorders(
            grid_variables=('RUSLE', 'delivered'),
            grid_timesteps=('monthly', 'total'),
            timeseries_variables=('RUSLE', 'delivered'),
            timeseries_timestep='1h',
        )

    Grids only, no timeseries::

        make_recorders = default_rusle_recorders(include_timeseries=False)

    Timeseries only, no grids::

        make_recorders = default_rusle_recorders(include_grids=False)

    For ensemble runs with dask (percentiles for exceedance plots)::

        make_recorders = default_rusle_recorders(timeseries_mode='percentiles')
        run_rusle_all_replicates(proj, rainfall, recorder_factory=make_recorders)
    """
    if timeseries_mode == 'none':
        include_timeseries = False

    # Convert timeseries_timestep to an agg_count
    ts_delta = pd.Timedelta(timeseries_timestep)
    agg_count = max(1, int(ts_delta / _MODEL_TIMESTEP))

    def factory(project, start, end):
        start = pd.Timestamp(start)
        end = pd.Timestamp(end)

        recorders = {}

        # --- Grid recorders: product of variables × fns × timesteps ---
        if include_grids:
            for ts_type in grid_timesteps:
                periods = _compute_periods(start, end, ts_type)
                for variable in grid_variables:
                    for fn in grid_fns:
                        key = f'{variable}_{fn}_{ts_type}'
                        recorders[key] = record_multi_period_grid(
                            variable, fn, periods,
                        )

        # --- Transform recorder ---
        if include_transform:
            recorders['the_transform'] = record_grid_transform()

        # --- Subcatchment timeseries ---
        if include_timeseries:
            _add_timeseries_recorders(project, recorders)

        return recorders

    def _add_timeseries_recorders(project, recorders):
        for ts_var in timeseries_variables:
            base_ts = record_subcatchment_timeseries(
                project,
                ts_var,
                fn=timeseries_fn,
                label_field=timeseries_label_field,
                agg_count=agg_count,
            )
            # Key includes variable name when there are multiple variables,
            # otherwise uses the standard constant for backward compatibility.
            if len(timeseries_variables) == 1:
                ts_key = c.RUSLE_OP_TIMESERIES_NAME
            else:
                ts_key = f'{ts_var}_{c.RUSLE_OP_TIMESERIES_NAME}'

            if timeseries_mode == 'full':
                recorders[ts_key] = base_ts

            elif timeseries_mode == 'percentiles':
                def _make_percentiles(base):
                    def pct_recorder(timestep, **data):
                        return base(timestep, **data)

                    def _reset():
                        base.reset()

                    def _finalize():
                        df = base.finalize()
                        if df is None or df.empty:
                            return pd.DataFrame()
                        pctiles = np.arange(101)
                        result = df.apply(
                            lambda col: np.percentile(col, pctiles)
                        )
                        result.index = pctiles
                        result.index.name = 'percentile'
                        return result

                    pct_recorder.reset = _reset
                    pct_recorder.finalize = _finalize
                    return pct_recorder

                recorders[ts_key + '_percentiles'] = _make_percentiles(base_ts)

            else:
                raise ValueError(
                    f"Unsupported timeseries_mode='{timeseries_mode}'. "
                    "Use 'full', 'percentiles', or 'none'."
                )

    return factory
