from affine import Affine
import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio.mask import mask
from rasterio.warp import reproject, Resampling
import os
import logging
import time
from fire_impacts import const as c
from fire_impacts.const import M2_TO_HA, MILLIGRAMS_TO_KILOGRAMS
from fire_impacts.pre.util import read_aligned, read_raster
from fire_impacts.util import load_package_data
logger = logging.getLogger(__name__)

from fire_impacts.pre import FireImpactsProject
from fire_impacts.pre.project import save_catchment_raster

DNBR_SEVERITY_THRESHOLD = 400
EMPIRICAL_COEFFICIENT = 0.082
LOG_INTERVAL_SECONDS = 15.0

###############################################################################
def compute_klscp_layer(
    proj:FireImpactsProject,
    catchment:str,
    support_practice_factor:float=1.0
    ):
    """
    Using previously-generated C, K, and LS factor rasters, generate
    a raster layer of the KLSCP values for the catchment.

    Returns: None

    Writes: A KLSCP raster (.tif) to the Erodibility folder of the
    current project/catchment.
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    # Read all input rasters and ensure they align:
    c_factor_path = proj.catchment_path(
        catchment,
        'Erodibility','C_factor_adjusted.tif'
        )
    k_factor_path = proj.catchment_path(
        catchment,
        'Erodibility',
        'K_factor_adjusted.tif'
        )
    ls_factor_path = proj.catchment_path(
        catchment,
        'Erodibility',
        'LS_factor.tif'
        )

    # Calculate values for the new layer and write them to a new raster:
    with rasterio.open(c_factor_path) as c_factor, \
         rasterio.open(k_factor_path) as k_factor, \
         rasterio.open(ls_factor_path) as ls_factor:

        # Read data as arrays
        c_array = c_factor.read(1)
        k_array = k_factor.read(1)
        ls_array = ls_factor.read(1)

        # Copy the profile metadata before exiting the `with` block.
        #We pick a layer where the nodata value is np.nan:
        new_meta_profile = ls_factor.meta.copy()

        # Perform the multiplication for RUSLE base layer
        base = c_array * k_array * ls_array
        base = base * support_practice_factor

        # Save the result as a raster layer
        base_raster_path = proj.catchment_path(
            catchment,
            'Erodibility',
            'KLSCP.tif'
            )
        # Update the metadata:
        new_meta_profile.update(
            dtype=rasterio.float32,
            count=1,
            compress='lzw'
            )

        # Write the new array with the new metadata to the relevant
        #project folder:
        with rasterio.open(base_raster_path, 'w', **new_meta_profile) as dst:
            dst.write(base, 1)

###############################################################################
def _rusle_parameter_grids(project:FireImpactsProject, catchment:str):
    """
    Organise relevant raster parameters and return them as usable
    data objects ready for rusle calculations.

    Parameters:
    - project (FireImpactsProject object): The current project, which
    should already have the relevant rasters saved in its directories.
    - catchment (string): Name of the catchment to get the grids for.

    Returns:
    - The data ONLY (as an array), for KLSCP, SDR, and DNBR.
    - The cell area (in hectares) and the raster transform object,
    which should be usable by all three data arrays.
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    cell_area_m2 = project.cell_area(catchment)
    cell_area_ha = cell_area_m2 * M2_TO_HA  # Convert to hectares

    # Generate a KLSCP raster to simplify analysis:
    compute_klscp_layer(project,catchment)

    # Now read that raster into memory:
    klscp, klscp_meta = read_raster(
        project.catchment_path(
            catchment,
            'Erodibility',
            'KLSCP.tif'
            )
        )

    transform = klscp_meta['transform']
    crs = klscp_meta['crs']

    # Get the Sediment Delivery Ratio (SDR) raster, which is generated
    #ultimately by the calculate_lumped_rusle() function in this module:
    sdr,_ = read_raster(
        project.catchment_path(
            catchment,
            'Delivery',
            'SDR.tif'
            )
        )

    # Get the delta Normalised Burn Ratio (dNBR) raster, which is
    #generated by severity.calculate_fire_severity(). Use read_aligned
    #to ensure it's in the same CRS as the RUSLE layers.
    # Do we need to do this? Why don't we do it for SDR too?
    dnbr = read_aligned(
        project.catchment_path(
            catchment,
            'FireSeverity',
            'masked_dNBR.tif'
            ),
        transform,
        crs,
        klscp.shape
        )
    return klscp, sdr, dnbr, cell_area_ha, transform

###############################################################################
def lumped_daily_rusle(project:FireImpactsProject, rainfall, catchment=None):
    """
    Calculates RUSLE and SDR erosion values for sub-catchments based on 30min rainfall sequence.

    Parameters:
    - project (fire_impacts.FireImpactsProject): Current project
    - rainfall (Series-like): 30 minute rainfall data (mm)
    - catchment (str): Name of the catchment to process. If None, process all catchments.

    Returns:
    - RUSLE_df (DataFrame): DataFrame summarizing RUSLE and sediment delivery results.
    """
    if catchment is None:
        return project.for_each_catchment(lambda c: lumped_daily_rusle(project,rainfall,c))

    if 'units' not in rainfall.attrs:
        logger.warning("Rainfall data has no units attribute, assuming units are correct (mm)")
    elif rainfall.attrs['units'] != 'mm':
        logger.error("Rainfall data has units '%s', expected 'mm'", rainfall.attrs['units'])
        raise ValueError("Rainfall data has units '%s', expected 'mm'"%rainfall.attrs['units'])
    RUSLE_df = calculate_lumped_rusle(project.get_subcatchments(catchment), rainfall, *_rusle_parameter_grids(project,catchment))

    logger.info('Done')
    return RUSLE_df

###############################################################################
def record_summary_grid(variable,fn='sum',start_time=None,end_time=None):
    '''
    Build a RUSLE recorder that summarizes a grid variable over time.

    Parameters:
    - variable (str): Name of the variable to summarize.
    - fn (str): Summary function to use: 'sum', 'mean', 'max'. Default is 'sum'.
    - start_time (datetime): OPTIONAL: Start time for the summary. If None, use the start of the simulation.
    - end_time (datetime): OPTIONAL: End time for the summary. If None, use the end of the simulation.
    Returns:
    - grid_recorder (function): A recorder function that can be used in the simulation (see: run_usle_simulation).
    '''
    result = None
    count = 0
    def grid_recorder(timestep,**kwargs):
        nonlocal result, count
        count += 1
        if start_time is not None and timestep < start_time:
            return result
        if end_time is not None and timestep > end_time:
            return result

        data = kwargs[variable]
        if result is None:
            result = data
        elif fn=='max':
            result = np.maximum(result, data)
        else:  # sum or mean
            result += data
        if fn=='mean':
            return result / count

        return result

    def reset():
        nonlocal result, count
        result = None
        count = 0

    def finalize():
        nonlocal result, count
        if fn=='mean':
            return result / count
        return result
    grid_recorder.reset = reset
    grid_recorder.finalize = finalize

    return grid_recorder

###############################################################################
def record_subcatchment_timeseries(
    proj:FireImpactsProject,
    variable_name:str,
    fn="sum",
    label_field=None,
    agg_count=1
    ):
    """
    Build a RUSLE recorder that summarizes a variable over
    subcatchments

    Parameters:
    - proj (fire_impacts.FireImpactsProject): Current project
    - variable_name (str): Name of the variable to summarize.
    - fn (str): Summary function to use: 'sum', 'mean', 'max'. Default
    is 'sum'.
    - label_field (str): OPTIONAL: Field in the catchment boundaries to
    use as labels. If None, use the index.
    - agg_count (int): OPTIONAL: Number of timesteps to aggregate
    before recording. Default is 1

    Returns:
    - timeseries_recorder (function): A recorder function that can be
    used in the simulation (see: run_usle_simulation).
    --------------------------------------------------------------------
    Notes:
    - While the time series can always be resampled to a desired
    timestep AFTER the simulation, the agg_count parameter can be used
    to speed things up significantly by aggregating (sum) over multiple
    timesteps during the simulation itself.
    - agg_count would only be 1 if the value in the data was already in
    the desired time series interval i.e. if you were making a daily
    timeseries and had one 'row' per day in the data.
    --------------------------------------------------------------------
    """
    result = None
    index = None
    zones = None
    zone_names = None

    intermediate=None
    intermediate_count = 0
    ###########################################################################
    def timeseries_recorder(timestep,catchment,transform,**kwargs):
        """
        Primary closure function for building a timeseries of
        aggregated values.

        Parameters:
        - timestep:
        - catchment (str): Name of the catchment currently being worked
        with
        - transform: Rasterio transform object used for converting
        polygons to raster

        Returns:
        - None until the number of timesteps processed equals the
        requested number of aggregations, then a dictionary of arrays
        with one key:value pair for each zone.
        ----------------------------------------------------------------
        ----------------------------------------------------------------
        """
        # Declare the variables defined in the next function layer out
        #so this inner function will remember their values between
        #calls:
        # Row labels (index) and aggregated values (results) that will
        #be used to build the final dataframe:
        nonlocal result, index
        # The spatial zones, and their corresponding zone names, for
        #which aggregated values will be recorded in the timeseries.
        #Each zone will be a column in the final output with the zone
        #name as the column label:
        nonlocal zones, zone_names
        # intermediate will start as just the variable name, and then
        #it will be a string with a copy of the variable name for each
        #time this has been run (why?). intermediate_count is the
        #number of times this has happened.
        nonlocal intermediate, intermediate_count

        # kwargs here is a dictionary of some single values like 'total
        #rain' and 'erosivity', and some arrays for things like 'RUSLE'
        #and SDR.
        data = kwargs.get(variable_name)
        # Throw an error if variable name hasn't been provided:
        if data is None:
            raise ValueError(
                f"Variable {variable_name} not found in simulation data."
                )
        # If zones haven't been provided, we still need an area for
        #consistent behaviour:
        if zones is None:
            # Use the catchment boundary as the single zone for the
            #current catchment:
            boundaries_v = proj.catchment_boundary(catchment)#.to_crs(epsg=4326)
            # List method to build an array of rasters the same shape
            #as the catchment boundary:
            zones = [
                rasterio.features.rasterize(
                    [g], # The geometry (see 'for g in ...')
                    transform=transform,
                    fill=np.nan,
                    dtype=np.float32,
                    out_shape=data.shape
                    ) for g in boundaries_v.geometry
                ]
            # If the user hasn't provided a column label for a column
            #which includes the name for each zone:
            if label_field is None:
                # Just use the index as the zone names if no label field:
                zone_names = boundaries_v.index.values
            # If a column HAS been specified which includes the name
            #for each zone:
            else:
                # Get the values, noting that zones is none so this
                #will just be the single catchment boundary:
                zone_names = boundaries_v[label_field].values

        # Update the counter for the number of times this has been run:
        intermediate_count += 1
        if intermediate is None:
            intermediate = data
        else:
            # Data and intermediate are both arrays; intermediate is
            #the aggregation of all timesteps already recorded in the
            #current cycle, and data is the single values for the
            #new timestep currently being processed.
            # Note that these are 3D arrays, so when you add data to
            #intermediate it adds a new 2D array of the current set of
            #values, along the third dimension.
            intermediate += data

        # If we haven't yet reached the requested number of timesteps,
        #we haven't yet changed result so it will still be None.
        if intermediate_count < agg_count:
            return result
        # Once we've reached the requested agg count, store the whole
        #3D array as data and update intermediates to their starting
        #values.
        else:
            data = intermediate
            intermediate = None
            intermediate_count = 0
        # If there's not already an index specified, make an empty list
        #so we still have something to use:
        if index is None:
            index = []
        # Add the current timestep as the index value:
        index.append(timestep)

        # Make a copy of the set of arrays for each zone, where all the
        #values (cells) outside that zone will be NaN and those inside
        #will retain their values.
        masked = [data * zone for zone in zones]

        def agg(d):
            """
            Helper function to handle the requested aggregation
            """
            if fn == "sum":
                return np.nansum(d)
            elif fn == "mean":
                return np.nanmean(d)
            elif fn == "max":
                return np.nanmax(d)
            else:
                raise ValueError(f"Function {fn} not recognized.")

        # If there's not already a result, make a dictionary with a
        #list for every AoI:
        if result is None:
            result = {name: [] for name in zone_names}

        # For each zone-specific set of arrays, apply the requested
        #aggregation:
        grouped = [agg(d) for d in masked]
        # Using enumerate() on zone_names simply gives us an iterable
        #with a number for each zone name:
        for ix,name in enumerate(zone_names):
            # The key in result will be the zone name. The value will
            #be the array in grouped that is in the same position as
            #the current zone in zones.
            result[name].append(grouped[ix])

        return result

    ###########################################################################
    def reset():
        """
        Secondary closure function to revert all encapsulated variables
        to starting values.
        """
        # Access the encapsulated variables from the outer function:
        nonlocal result, index
        nonlocal zones, zone_names
        nonlocal intermediate, intermediate_count
        # Reset them all to their starting values:
        index = None
        zones = None
        zone_names = None
        result = None
        intermediate = None
        intermediate_count = 0

    ###########################################################################
    def finalize():
        """
        Secondary closure function
        """
        # Access the up-to-date result and index variables:
        nonlocal result, index
        # Go through each zone in the result dictionary and convert
        #the data to a numpy array (was it already one??)
        for key in result:
            result[key] = np.array(result[key])

        # Convert to a dataframe and return:
        return pd.DataFrame(result,index=index)

    # Add the two secondary closure functions as method-like
    #attachments to the main one
    timeseries_recorder.reset = reset
    timeseries_recorder.finalize = finalize
    return timeseries_recorder

###############################################################################
def run_usle_simulation(
    project:FireImpactsProject,
    rainfall,
    catchment=None,
    recorders=None,
    save_rasters:bool=True,
    save_timeseries:bool=True
    ):
    """
    Run the USLE simulation for a given project and rainfall data,
    recording results as specified.

    Parameters:
    - project (fire_impacts.FireImpactsProject): Current project
    - rainfall (Series-like): 30 minute rainfall data (mm)
    - catchment (str): Name of the catchment to process. If None,
    process all catchments.
    - recorders (dict): OPTIONAL: Dictionary of recorder functions to
    use during the simulation.
    - save_rasters (bool): Whether the output rasters should be saved 
    as GeoTIFF files to the results folder for the current catchment
    - save_timeseries (bool): Whether the daily timeseries should be 
    saved as a csv file to the results folder for the current catchment

    Returns:
    - results (dict): Dictionary of recorded results from the
    simulation.
    - params (tuple): Tuple of parameters used in the simulation
    (klscp, sdr, dnbr, cell_area_ha, transform).
    --------------------------------------------------------------------
    Notes:
    - Each recorder function should accept parameters
    (timestep, **data) and return recorded results.
    - The data dictionary passed to each recorder will contain keys
    such as 'RUSLE', 'SDR', etc.
    - Each recorder function should also have 'reset' and 'finalize'
    methods to manage state.
    --------------------------------------------------------------------
    """
    if catchment is None:
        return project.for_each_catchment(
            lambda c: run_usle_simulation(project,rainfall,c,recorders)
            )
    # If no recorders were passed, use an empty dictionary so the rest
    #of the code works consistently:
    if recorders is None:
        recorders = dict()
    # Reset each recorder so we're building new arrays for aggregation:
    for recorder in recorders.values():
        recorder.reset()

    # Get the relevant RUSLE parameters as handy arrays:
    params = _rusle_parameter_grids(project,catchment)
    klscp, sdr, dnbr, cell_area_ha, transform = params
    # Get the catchment boundary geometry in a form that's usable by
    #rasterio:
    catchment_boundary = project.catchment_boundary(catchment)
    # catchment_boundary = project.get_subcatchments(catchment).dissolve()
    geometry = catchment_boundary.geometry.values

    # Convert the catchment boundary to a raster with 1 for every cell
    #that's within the catchment boundary, and NaN for all others:
    mask = rasterio.features.rasterize(
        geometry,
        transform=transform,
        fill=np.nan,
        dtype=np.float32,
        out_shape=klscp.shape
        )

    # Use the mask to convert all values in the RUSLE grids that are
    #outside the catchment boundary to NaN:
    klscp_masked = klscp*mask
    sdr_masked = sdr*mask
    dnbr_masked = dnbr*mask

    # Empty dictionary to start filling with results:
    results = dict()
    # Iterate over each tuple of (timestep, values dict) produces by
    #the generate_rusle() generator function:
    for ts_data in generate_rusle(
        rainfall,
        klscp_masked,
        sdr_masked,
        dnbr_masked,
        cell_area_ha
        ):
        # Unpack the tuple elements:
        timestep, data = ts_data
        # Go through each encapsulating recorder function and load
        #the rusle data in for the current tuple:
        for key, recorder in recorders.items():
            results[key] = recorder(
                timestep,
                **data, # Unpack all values in the data dictionary
                catchment=catchment,
                transform=transform # from _rusle_parameter_grids() above
                )

    # Now that we've gone through all timesteps in the rainfall data,
    #get the final result. In the case of catchment timeseries, this
    #is a dataframe of the values aggregated for each of the specified
    #number of timesteps (48 for daily aggregation on half-hourly data).
    for key, recorder in recorders.items():
        results[key] = recorder.finalize()

    if save_rasters:
        template_raster = project.catchment_path(
            catchment,
            'Erodibility',
            'LS_factor.tif'
            )
        _, template_meta = read_raster(template_raster)
        for output_raster in c.RUSLE_OUTPUT_RASTER_NAMES:
            save_data = results[output_raster]
            save_catchment_raster(
                project=project,
                catchment_name=catchment,
                file_name=output_raster,
                section=c.RESULTS_FOLDER_NAME,
                data=save_data,
                meta=template_meta
                )

    if save_timeseries:
        out_name = project.catchment_path(
            catchment,
            c.RESULTS_FOLDER_NAME,
            c.RUSLE_OP_TIMESERIES_NAME + '.csv'
            )
        results[c.RUSLE_OP_TIMESERIES_NAME].to_csv(out_name)

    # Attach a pointer to all the rusle parameters (mostly grids) used
    #for these calcs:
    results['params'] = params

    return results

###############################################################################
def gridded_total_rusle(project:FireImpactsProject, rainfall, catchment=None):
    """
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    if catchment is None:
        return project.for_each_catchment(lambda c: lumped_daily_rusle(project,rainfall,c))
    result = None
    # Get an iterable of the boundaries of each subcatchment in the
    #project:
    subcatch_boundaries = project.get_subcatchments(catchment).iloc[0].geometry

    total_eroded = None
    total_delivered = None
    params = _rusle_parameter_grids(project,catchment)
    for day_data in generate_rusle_for_feature([subcatch_boundaries], rainfall, *params):
        day, _, _, _, \
        daily_RUSLE, daily_SDR, \
        _, _, _, _ = day_data
        # logger.info('Processing day %s',day)
        if total_eroded is None:
            total_eroded = daily_RUSLE
            total_delivered = daily_SDR
        else:
            total_eroded += daily_RUSLE
            total_delivered += daily_SDR

    logger.info('Done')
    return total_eroded, total_delivered, params[-1]

###############################################################################
def calculate_lumped_rusle(
    subcatchments:gpd.GeoDataFrame,
    rainfall:pd.DataFrame,
    klscp:np.array,
    sdr:np.array,
    dnbr:np.array,
    cell_area_ha:float,
    transform:Affine
    ):
    """
    --------------------------------------------------------------------
    --------------------------------------------------------------------
    """
    daily_erosion = []
    # Read catchment shapefile
    # Loop through each catchment
    for ind, subcatchment in subcatchments.iterrows():
        logger.info('Processing subcatchment %d',ind+1)
        #catchment_name = catchment['PRIMARY_CA']  # Replace 'PRIMARY_CA' with the appropriate field for catchment names
        geometry = [subcatchment['geometry']]

        for day_data in generate_rusle_for_feature(geometry, rainfall, klscp, sdr, dnbr, cell_area_ha, transform):
            day, daily_total_rain, max_intensity, max_erosivity, \
            daily_RUSLE, daily_SDR, \
            daily_RUSLE_below_threshold, daily_RUSLE_above_threshold, \
            daily_SDR_below_threshold, daily_SDR_above_threshold = day_data

            # Store the daily result in the dictionary
            daily_erosion.append({
                'Sub-catchment': f"Sub_{ind+1}",
                # 'Simulation': sim.item()+1,
                'Day': day,
                'Rainfall (total daily)': daily_total_rain,
                'Max Rain Intensity (30 mins)': max_intensity,
                'Max Erosivity (30 mins)': max_erosivity,
                'RUSLE': np.nansum(daily_RUSLE),
                'RUSLE_SDR': np.nansum(daily_SDR),
                'RUSLE (Low severity)': np.nansum(daily_RUSLE_below_threshold),
                'RUSLE (High severity)': np.nansum(daily_RUSLE_above_threshold),
                'RUSLE_SDR (Low severity)': np.nansum(daily_SDR_below_threshold),
                'RUSLE_SDR (High severity)': np.nansum(daily_SDR_above_threshold),
            })
        #-------For some reason this code was docstrung previously:-----
        # Save the output raster
        # rusle_path = os.path.join(output_path, f"{catchment_name}_RUSLE_sim{sim.item()}_{day.item()}.tif")
        # with rasterio.open(rusle_path, 'w', **profile) as dst:
        #     dst.write(daily_RUSLE, 1)

        # sdr_rusle_path = os.path.join(output_path, f"{catchment_name}_SDR_RUSLE_sim{sim.item()}_{day.item()}.tif")
        # with rasterio.open(sdr_rusle_path, 'w', **profile) as dst:
        #     dst.write(daily_SDR_RUSLE, 1)
        #---------------------------------------------------------------

    # Convert the results to a DataFrame for analysis or saving
    RUSLE_df = pd.DataFrame(daily_erosion)
    # Read constituent data and convert it to ratio (its in mg per kg)
    # constituent_df = pd.read_csv(Constituent_path)
    RUSLE_df = compute_particulates(RUSLE_df)

    # Save to a CSV file if needed
    RUSLE_df=RUSLE_df.round(1)
    logger.info('Done')
    return RUSLE_df

###############################################################################
def generate_rusle(
    rainfall:pd.Series,
    klscp:np.array,
    sdr:np.array,
    dnbr:np.array,
    cell_area_ha:float
    ):
    """
    Generator function that produces an iterable of (timestep, dict)
    tuples for each timestep entry in the provided rainfall data. Dict
    is a lookup of all relevant RUSLE results for that timestep.

    Parameters:
    - rainfall (pd.Series like): Series with 30-minute rainfall data.
    Must be DEPTH values in mm.
    - klscp (np.array): Raster layer with KLSCP values.
    - sdr (np.array): Raster layer with SDR values.
    - dnbr (np.array): Raster layer with dNBR values.
    - cell_area_ha (float): Area of each cell in hectares.

    Yields:
    - Tuple with timestep and dict with results like
    (timestep (datetime), dict with keys)
    - Dictionary has the following keys and value types:
        - 'total_rain' (float)
        - 'intensity' (float)
        - 'erosivity' (float)
        - 'RUSLE' (np.array)
        - 'SDR' (np.array)
        - 'RUSLE_below_threshold' (np.array)
        - 'RUSLE_above_threshold' (np.array)
        - 'SDR_below_threshold' (np.array)
        - 'SDR_above_threshold' (np.array))
    --------------------------------------------------------------------
    Notes:
    - This is a GENERATOR function which will return results as an
    iterable rather than one big dataset. Suits the use of recorders.
    - klscp, sdr and dnbr should have the same shape and transformation.
    --------------------------------------------------------------------
    """
    # Convert to Series if we've got a dataframe, to ensure consistency:
    if isinstance(rainfall, pd.DataFrame):
        rainfall = pd.Series(data=rainfall['rainfall'], index=rainfall.index)
    # Pre-compute severity masks based on dNBR thresholds
    dnbr_below_threshold = dnbr < DNBR_SEVERITY_THRESHOLD
    dnbr_above_threshold = dnbr >= DNBR_SEVERITY_THRESHOLD

    # Initialize timing variables for progress logging
    total_timesteps = len(rainfall.index)
    start_time = time.time()
    last_log_time = start_time
    iteration_count = 0

    # Loop over each 30-min timestep
    for timestep in rainfall.index:
        iteration_count += 1
        # Get rainfall amount (∆V_r) during the 30-min period
        delta_v_r = rainfall[timestep]

        # Initialize result dict
        result = {
            'total_rain': delta_v_r,
            'intensity': 0.0,
            'erosivity': 0.0,
            'RUSLE': np.zeros_like(klscp, dtype=np.float32),
            'SDR': np.zeros_like(klscp, dtype=np.float32),
            'RUSLE_below_threshold': np.zeros_like(klscp, dtype=np.float32),
            'RUSLE_above_threshold': np.zeros_like(klscp, dtype=np.float32),
            'SDR_below_threshold': np.zeros_like(klscp, dtype=np.float32),
            'SDR_above_threshold': np.zeros_like(klscp, dtype=np.float32),
        }

        # Skip calculations if delta_v_r is 0
        if delta_v_r == 0:
            yield (timestep, result)
            continue

        # Calculate rainfall intensity (∆V_r / ∆t_r)
        intensity = delta_v_r / 0.5  # mm/hr
        result['intensity'] = intensity

        # Calculate unit kinetic energy (e_r)
        e_r = 0.29 * (1 - 0.72 * np.exp(-EMPIRICAL_COEFFICIENT * intensity))

        # Calculate energy (E)
        E = e_r * delta_v_r

        # Calculate erosivity factor (R)
        R = E * intensity
        result['erosivity'] = R

        # Calculate RUSLE
        # TODO: sediment eroded? kg? t?
        RUSLE = (R * klscp) * cell_area_ha  # Total erosion in tonnes per hectare
        result['RUSLE'] = RUSLE

        # Calculate SDR_RUSLE
        # TODO: sediment delivered? kg? t?
        SDR_RUSLE = RUSLE * sdr  # Delivered erosion/sediment
        result['SDR'] = SDR_RUSLE

        # Apply severity masks
        result['RUSLE_below_threshold'] = np.where(dnbr_below_threshold, RUSLE, 0)
        result['RUSLE_above_threshold'] = np.where(dnbr_above_threshold, RUSLE, 0)
        result['SDR_below_threshold'] = np.where(dnbr_below_threshold, SDR_RUSLE, 0)
        result['SDR_above_threshold'] = np.where(dnbr_above_threshold, SDR_RUSLE, 0)

        # Check if LOG_INTERVAL_SECONDS have elapsed since last log
        current_time = time.time()
        if current_time - last_log_time >= LOG_INTERVAL_SECONDS:
            progress_pct = (iteration_count / total_timesteps) * 100
            elapsed_time = current_time - start_time
            avg_time_per_iteration = elapsed_time / iteration_count
            remaining_iterations = total_timesteps - iteration_count
            estimated_time_remaining = avg_time_per_iteration * remaining_iterations

            # Format time remaining as hours:minutes:seconds
            hours, remainder = divmod(int(estimated_time_remaining), 3600)
            minutes, seconds = divmod(remainder, 60)
            time_str = f"{hours:02d}:{minutes:02d}:{seconds:02d}" if hours > 0 else f"{minutes:02d}:{seconds:02d}"

            logger.info(
                f"Progress: {iteration_count}/{total_timesteps} timesteps "
                f"({progress_pct:.1f}%) - Current timestep: {timestep} - "
                f"Estimated time remaining: {time_str}"
            )
            last_log_time = current_time

        yield (timestep, result)

def generate_rusle_for_feature(geometry:list, rainfall:pd.DataFrame, klscp:np.array, sdr:np.array, dnbr:np.array, cell_area_ha:float, transform:Affine):
    '''
    Calculates RUSLE and SDR erosion values for sub-catchments based on rainfall simulations.

    Parameters:
    - geometry (list): List of shapely geometries representing the sub-catchment.
    - rainfall (pd.Series like): Series with 30-minute rainfall data.
    - klscp (np.array): Raster layer with KLSCP values.
    - sdr (np.array): Raster layer with SDR values.
    - dnbr (np.array): Raster layer with dNBR values.
    - cell_area_ha (float): Area of each cell in hectares.
    - transform (Affine): Affine transformation for the raster layers.

    klscp, sdr and dnbr should have the same shape and transformation.

    Yield:
    - Tuple with daily results for the sub-catchment:
      day (datetime), daily_total_rain (float), max_intensity (float), max_erosivity (float),
      daily_RUSLE (np.array), daily_SDR (np.array),
      daily_RUSLE_below_threshold (np.array), daily_RUSLE_above_threshold (np.array),
      daily_SDR_below_threshold (np.array), daily_SDR_above_threshold (np.array)
    '''
    mask = rasterio.features.rasterize(geometry, transform=transform, fill=np.nan, dtype=np.float32, out_shape=klscp.shape)
    klscp_masked = klscp*mask
    sdr_masked = sdr*mask
    dnbr_masked = dnbr*mask

    days = pd.Series(rainfall.index.date).drop_duplicates()
    for day in days:
        rainfall_data = rainfall[rainfall.index.date==day]
        # Initialize daily arrays for RUSLE and SDR_RUSLE
        daily_RUSLE = np.zeros_like(klscp_masked, dtype=np.float32)
        daily_SDR = np.zeros_like(klscp_masked, dtype=np.float32)
        daily_total_rain = 0.0
        max_intensity = 0.0
        max_erosivity = 0.0

        # Loop over each 30-min interval
        for subday in rainfall_data.values:
            # Get rainfall amount (∆V_r) during the 30-min period
            # delta_v_r = rainfall_data.sel(subday_30mins=subday).values
            delta_v_r = subday
            daily_total_rain+=delta_v_r

            # Skip calculations if delta_v_r is 0
            if delta_v_r == 0: # What if spatial? max?
                continue

            # Calculate rainfall intensity (∆V_r / ∆t_r)
            intensity = delta_v_r / 0.5  # mm/hr
            max_intensity = max(max_intensity,intensity)

            # Calculate unit kinetic energy (e_r)
            e_r = 0.29 * (1 - 0.72 * np.exp(-EMPIRICAL_COEFFICIENT * intensity))

            # Calculate energy (E)
            E = e_r * delta_v_r

            # Calculate erosivity factor (R)
            R = E * intensity
            max_erosivity = max(max_erosivity,R)

            # Calculate RUSLE
            # TODO: sediment eroded? kg? t?
            RUSLE = (R * klscp_masked) * cell_area_ha # Total erosion in tonnes per hectare
            daily_RUSLE += RUSLE  # Accumulate RUSLE for the day

            # Calculate SDR_RUSLE
            # TODO: sediment delivered? kg? t?
            SDR_RUSLE = RUSLE * sdr_masked  # Delivered erosion/sediment
            daily_SDR += SDR_RUSLE  # Accumulate SDR_RUSLE for the day


        # Mask daily_RUSLE and daily_SDR_RUSLE for dNBR values
        dnbr_below_threshold = dnbr_masked < DNBR_SEVERITY_THRESHOLD
        dnbr_above_threshold = dnbr_masked >= DNBR_SEVERITY_THRESHOLD

        daily_RUSLE_below_threshold = np.where(dnbr_below_threshold, daily_RUSLE, 0)
        daily_RUSLE_above_threshold = np.where(dnbr_above_threshold, daily_RUSLE, 0)

        daily_SDR_below_threshold = np.where(dnbr_below_threshold, daily_SDR, 0)
        daily_SDR_above_threshold = np.where(dnbr_above_threshold, daily_SDR, 0)

        yield((day,daily_total_rain,max_intensity,max_erosivity,daily_RUSLE,daily_SDR,daily_RUSLE_below_threshold,daily_RUSLE_above_threshold,daily_SDR_below_threshold,daily_SDR_above_threshold))

def compute_particulates(rusle_df,constituents_df=None):
    if constituents_df is None:
        constituents_df = load_package_data('ash_constituents.csv')

    # Iterate through each constituent and severity
    for _, row in constituents_df.iterrows():
        particulate = row['Particulate constituent (ash)']
        low_severity = row['Low severity- mean amount (mgkg-1)'] * MILLIGRAMS_TO_KILOGRAMS
        high_severity = row['High severity- mean amount (mgkg-1)'] * MILLIGRAMS_TO_KILOGRAMS

        # Define new column name
        column_name = f"{particulate} (Tonne)"
        rusle_df[column_name] = (rusle_df['RUSLE_SDR (Low severity)'] * low_severity) + (rusle_df['RUSLE_SDR (High severity)'] * high_severity)
    return rusle_df


