# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.18.1
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Fire impacts simulations
#
# This notebook demonstrates the fire impacts simulation modules.
#
# It is assumed that you have a `FireImpactsProject` populated with all pre-processed data for the catchment.

# %%
import logging
logging.basicConfig(level=logging.INFO,format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

from fire_impacts.sim import rusle, aggregate_rainfall_data, debris_flow
from fire_impacts.stochastic.rainfall import get_rainfall_replicates
from fire_impacts import FireImpactsProject
from fire_impacts.pre.rusle import compute_sediment_delivery_ratio

import matplotlib.pyplot as plt


# %% [markdown]
# ## Load project

# %%
#proj = FireImpactsProject('.',exist_ok=True)
proj = FireImpactsProject('.', exist_ok=True)

# %%
proj.catchments

# %% [markdown]
# > **Note:** You can capture multiple study areas / catchments within a single `FireImpactsProject` directory structure. Here we will assume you have one, so we will take the first (presumed only)

# %%
catchment_name = proj.catchments[0]
catchment_name
# %%
subcatch_path = '..\\test_data\\Subcatchments_EgSmall_7899.shp'
#proj.add_subcatchments(catchment_name, subcatch_path)

# %% [markdown]
# ## Rainfall data
#
# Both the erosion (RUSLE) and debris flow modules rely on subdaily rainfall data. The erosion modules, demonstrated here, rely on 30 minute data, while the debris flow relies on 12 minute data.
#
# Furthermore, it is encouraged that both modules be run stochastically, using multiple rainfall replicates.
#
# The library provides functionality for processing stochastic rainfall data, generated by [pyraingen](https://github.com/crdykman/pyraingen). You can install pyraingen locally and calibrate it to available subdaily rainfall observations. Alternatively, you can call a remote pyraingen API and generate data based on publicly available data. We wil use the remote API in this example.

# %%
# The fire dates and recovery windows are properties of the project — they
# were set during PrepareData (fire severity + compute_adjusted_k_c) and
# stored in the catchment's run-context. The simulation period is therefore
# computed (fire end date -> end of the last recovery window) rather than
# hard-coded here.
rain_data_start, rain_data_end = proj.get_simulation_period(catchment_name)

# `num_years` is inferred from start/end (one API year per calendar
# year spanned).  `mean_annual_rainfall` and `average_temperature` are
# optional — if omitted, the backend service estimates them from the
# catchment's lat/lon.  Override them here when you have site-specific
# climate statistics.
replicates = get_rainfall_replicates(
    proj,
    catchment=None,
    start=rain_data_start,
    end=rain_data_end,
    num_replicates=10,
    # mean_annual_rainfall=600,   # mm  — optional
    # average_temperature=20,     # °C  — optional
)
rainfall_data = replicates[catchment_name]
# %% [markdown]
# Once we have our pyraingen rainfall replicates, we use `aggregate_rainfall_data()` to resample the results to the 30-minute frequency required for debris flow simulations

# %%
# aggregate_rainfall_data?

# %%
rainfall_30min = aggregate_rainfall_data(rainfall_data,rain_data_start,rain_data_end)

# %%
# You can inspect the aggregated rainfal data object if required:
rainfall_30min

# %% [markdown]
# **Note:** The pyraingen data includes 10 stochastic replicates. In the following examples, we will only use one replicate.
#

# %% [markdown]
# ## Erosion/RUSLE: Daily Simulation
#
# Erosion processed are modelled cell-by-cell, timestep-by-timestep.
#
# This can result in a large amount of output that in most cases is not directly usable.
#
#  The library currently multiple ways to extract data from the model as it runs via customisable 'recorders'.
#

# %%
# Grab a single rainfall sequence from the stochastic rainfall replicates and inspect it:
rain_seq = rainfall_30min.rainfall[:,9].to_pandas()
rain_seq

# %% [markdown]
# ### Setting up recorders
#
# We want multiple gridded outputs:
# * Total erosion for the year following the fire (year 1),
# * Total erosion for the second year post fire
# * Peak 30 min erosion for year 1 and for year 2
# * The same stats for sediment *delivered* to streams
#
# We also want daily timeseries at the subcatchment scale that we can later import into Source

# %%
# Define the end of year 1 and the start of year 2
y1_end = rain_seq.index[len(rain_seq)//2]
y2_start = rain_seq.index[1+len(rain_seq)//2]

# %%
recorders = dict(
    erosion_total=rusle.record_summary_grid('RUSLE'),
    peak_erosion=rusle.record_summary_grid(
        'RUSLE',
        fn='max',
    ),
    delivered_total=rusle.record_summary_grid(
        'delivered',
    ),
    peak_delivered=rusle.record_summary_grid(
        'delivered',
        fn='max',
    ),
    erosion_daily_time_series=
        rusle.record_subcatchment_timeseries(
            proj,
            'RUSLE',
            agg_count=48,
        ),
)

# %%

# %% [markdown]
# ### Run the simulation

# %%
# run_usle_recovery_series splits the rainfall across the recovery windows
# defined in the run-context and runs each one against its matching
# fire-adjusted layers. No fire dates or recovery times are specified here.
results = rusle.run_usle_recovery_series(
    proj,
    rain_seq,
    recorders=recorders,
)

# %% [markdown]
# ### Baseline (no-fire) simulation
#
# To isolate the fire-attributable component of the erosion, we re-run
# the same simulation using the **unadjusted** C and K factors — i.e. as
# if the catchment had not burned. Outputs land in a sibling
# ``Results_baseline/`` folder so they sit alongside, rather than
# overwriting, the fire-impacted results. Differencing the two gives
# the erosion uplift caused by the fire.

# %%
# Rebuild the recorders: each recorder carries accumulator state from
# the fire run, so we need fresh ones for the baseline.

compute_sediment_delivery_ratio(
    proj,
    catchment_name,
    c_factor_path=proj.catchment_path(
        catchment_name,
        'Erodibility',
        'C_factor.tif',
    ),
    output_suffix='baseline',
)

baseline_recorders = dict(
    erosion_total=rusle.record_summary_grid('RUSLE'),
    peak_erosion=rusle.record_summary_grid(
        'RUSLE',
        fn='max',
    ),
    delivered_total=rusle.record_summary_grid(
        'delivered',
    ),
    peak_delivered=rusle.record_summary_grid(
        'delivered',
        fn='max',
    ),
    erosion_daily_time_series=
        rusle.record_subcatchment_timeseries(
            proj,
            'RUSLE',
            agg_count=48,
        ),
)
baseline_results = rusle.run_usle_recovery_series(
    proj,
    rain_seq,
    recorders=baseline_recorders,
    use_fire_adjusted=False,
)

# %% [markdown]
# ### Viewing RUSLE simulation results
#
# One easy, intuitive way to view the rsults is as a daily timeseries of total mass eroded each day. This is embedded within the `results` object created above

# %%
# results is keyed {catchment: {recovery_time: recorder-results}}.
catchment_results = results[catchment_name][0]  # or results[catchment_name][0.5], etc.
catchment_results['erosion_daily_time_series']

# %% [markdown]
# You can also visualise the various outputs.
# - To view the results for the whole catchment as a raster, use `plot_catchment_raster()`
#     - Specify the recovery-specific results folder (e.g. *'Results_t0'*) so the plotting function knows where to look
# - To view results aggregated by subcatchment, use `plot_subcatchments()`
#     - Specify the catchment name, the recovery-specific results folder (`data_type`), and the data type you want to see
#     - The data will be aggregated for each subcatchment using the most appropriate aggregation:
#         - Sum for totals (e.g. 'erosion_total', 'delivered_total')
#         - Mean for peaks (e.g. 'peak_erosion', 'peak_delivered')
#
# Examples of the different visualisations for our example catchment are shown in the following cells
# > **Note**: The code will show warnings if no aggregation is specified, so it is absolutely clear how values are being aggregated from rasters to subcatchments

# %%
# To see a complete picture of sediment eroded across the catchment:
proj.plot_catchment_raster('Results_t0','erosion_total')

# %%
# To see the total sediment eroded across each subcatchment:
# The recovery-specific results folder must be given explicitly (e.g.
# 'Results_t0'); otherwise the summary CSV defaults to the old 'Results'
# folder, which no longer exists.
proj.plot_subcatchments(catchment=catchment_name, data_type='Results_t0', colour_col='erosion_total')

# %%
# To see the maximum erosion for any 30-minute period for each cell:
proj.plot_catchment_raster('Results_t0', 'peak_erosion')

# %%
# To see the average maximum erosion in any 30-minute period across subcatchments:
proj.plot_subcatchments(catchment=catchment_name, data_type='Results_t0', colour_col='peak_erosion')

# %% [markdown]
# Once we've predicted how much sediment has *eroded* from each cell, the final RUSLE step is to work out how much of that eroded sediment actually makes its way downhill and is *delivered* to the stream network.

# %%
# Total sediment delivered to streams during the first year:
proj.plot_catchment_raster('Results_t0',  'delivered_total')

# %%
# Totals delivered from each subcatchment:
proj.plot_subcatchments(catchment=catchment_name, data_type='Results_t0', colour_col='delivered_total')

# %%
# Largest mass of sediment delivered during any 30-minute period for each cell:
proj.plot_catchment_raster('Results_t0', 'peak_delivered')

# %%
# Average maximum sediment delivered during any 30-minute period across each subcatchment:
proj.plot_subcatchments(catchment=catchment_name, data_type='Results_t0', colour_col='peak_delivered')

# %% [markdown]
# ## Debris Flow Simulation
#
# Debris flow operates on headwaters only and uses 12 minute rainfall _intensity_ data.
#
# The first thing we need to do is convert the rainfall *depth* values provided by pyraingen, to *intensity* values and then resample to 12-minute intervals
#

# %%
from fire_impacts.sim import convert_rainfall_depth_to_intensity

# %%
rainfall_intensity = convert_rainfall_depth_to_intensity(rainfall_data)
rainfall = aggregate_rainfall_data(rainfall_intensity,rain_data_start,rain_data_end,time_res='12min')
rainfall.rainfall

# %%
# Extract and inspect one replicate:
rain_intensity_seq = rainfall.rainfall[:,9].to_pandas()
rain_intensity_seq
# %% [markdown]
# ### Run the simulation

# %%
df_results = debris_flow(proj,rain_intensity_seq)

# %% [markdown]
# ### Viewing debris flow simulation results
#
# A table of results for each headwater will be saved to the project's **DebrisFlow** folder. A separate table will also be created with the same results aggregated to subcatchments.
#
# The easiest way to interpret the results is to use the build in visualisation methods: `plot_headwaters()` and `plot_subcatchments()`.
#
# > **Note**: For this example, and in many cases, rainfall intensity values might be below the threshold required to initiate a debris flow in any of the headwaters.

# %%
# To see the calculated critical thresholds for debris flow:
proj.plot_headwaters(catchment_name, 'I12_crit_mean_Year_1')

# %%
# The same, aggregated as the average threshold for each subcatchment:
proj.plot_subcatchments(catchment_name, 'DebrisFlow', 'I12_crit_mean_Year_1')

# %%
# To see the number of debris flow events in each headwater:
proj.plot_headwaters(catchment_name, 'Year1_num_events')

# %%
# And by subcatchment:
proj.plot_subcatchments(catchment_name, 'DebrisFlow', 'Year1_num_events')

# %%
# Finally we can view the mass that would form part of a debris flow in each subcatchment:
proj.plot_subcatchments(catchment_name, 'DebrisFlow', 'mass')

# %%
