# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.0
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Fire impacts simulations
#
# This notebook demonstrates the fire impacts simulation modules.
#
# It is assumed that you have a `FireImpactsProject` populated with all pre-processed data for the catchment.

# %%
import logging
logging.basicConfig(level=logging.INFO,format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

from fire_impacts.sim import rusle, aggregate_rainfall_data, debris_flow
from fire_impacts.stochastic.rainfall import get_rainfall_replicates
from fire_impacts import FireImpactsProject
from fire_impacts.context import RunContext

import matplotlib.pyplot as plt


# %% [markdown]
# ## Load project

# %%
#proj = FireImpactsProject('.',exist_ok=True)
proj = FireImpactsProject('.', exist_ok=True)

# %%
proj.catchments

# %% [markdown]
# > **Note:** You can capture multiple study areas / catchments within a single `FireImpactsProject` directory structure. Here we will assume you have one, so we will take the first (presumed only)

# %%
catchment_name = proj.catchments[0]

# A simulation binds to one (catchment, event, ensemble) combination
# via a RunContext. The event must match a directory produced by
# PrepareData; the ensemble names this climate realisation. Outputs
# land under Catchments/<c>/Runs/<event>/<ensemble>/.
ctx = RunContext.solo_run(
    proj, event='2019_fire', ensemble='stochastic',
)
ctx
# %%
subcatch_path = '..\\test_data\\Subcatchments_EgSmall_7899.shp'
#proj.add_subcatchments(catchment_name, subcatch_path)

# %% [markdown]
# ## Rainfall data
#
# Both the erosion (RUSLE) and debris flow modules rely on subdaily rainfall data. The erosion modules, demonstrated here, rely on 30 minute data, while the debris flow relies on 12 minute data.
#
# Furthermore, it is encouraged that both modules be run stochastically, using multiple rainfall replicates.
#
# The library provides functionality for processing stochastic rainfall data, generated by [pyraingen](https://github.com/crdykman/pyraingen). You can install pyraingen locally and calibrate it to available subdaily rainfall observations. Alternatively, you can call a remote pyraingen API and generate data based on publicly available data. We wil use the remote API in this example.

# %%
# The fire dates and recovery windows were set during PrepareData (fire
# severity + compute_adjusted_k_c) and stored in the event's FireMeta.csv /
# event.json. The simulation period is therefore read back from the context
# (fire end date -> end of the last recovery window) rather than hard-coded.
rain_data_start, rain_data_end = ctx.simulation_period()

# `num_years` is inferred from start/end (one API year per calendar
# year spanned).  `mean_annual_rainfall` and `average_temperature` are
# optional — if omitted, the backend service estimates them from the
# catchment's lat/lon.  Override them here when you have site-specific
# climate statistics.
# The generated rainfall is cached under Ensembles/<ensemble>/ and reused
# on repeat runs — identical rainfall, no repeat API call. Pass
# regenerate=True to force a fresh draw.
replicates = get_rainfall_replicates(
    ctx,
    start=rain_data_start,
    end=rain_data_end,
    num_replicates=10,
    # mean_annual_rainfall=600,   # mm  — optional
    # average_temperature=20,     # °C  — optional
)
rainfall_data = replicates
# %% [markdown]
# Once we have our pyraingen rainfall replicates, we use `aggregate_rainfall_data()` to resample the results to the 30-minute frequency required for debris flow simulations

# %%
# aggregate_rainfall_data?

# %%
rainfall_30min = aggregate_rainfall_data(rainfall_data,rain_data_start,rain_data_end)

# %%
# You can inspect the aggregated rainfal data object if required:
rainfall_30min

# %% [markdown]
# **Note:** The pyraingen data includes 10 stochastic replicates. In the following examples, we will only use one replicate.
#

# %% [markdown]
# ## Erosion/RUSLE: Daily Simulation
#
# Erosion processed are modelled cell-by-cell, timestep-by-timestep.
#
# This can result in a large amount of output that in most cases is not directly usable.
#
#  The library currently multiple ways to extract data from the model as it runs via customisable 'recorders'.
#

# %%
# Grab a single rainfall sequence from the stochastic rainfall replicates and inspect it:
rain_seq = rainfall_30min.rainfall[:,9].to_pandas()
rain_seq

# %% [markdown]
# ### Setting up recorders
#
# We want multiple gridded outputs:
# * Total erosion for the year following the fire (year 1),
# * Total erosion for the second year post fire
# * Peak 30 min erosion for year 1 and for year 2
# * The same stats for sediment *delivered* to streams
#
# We also want daily timeseries at the subcatchment scale that we can later import into Source

# %%
# Recorders are built with the default_rusle_recorders() factory: it returns
# a factory(ctx, start, end) that produces a fresh recorder set. Here we ask
# for whole-period ('total') grids of RUSLE and delivered sediment, each as a
# sum and a peak, plus a daily subcatchment timeseries. Other grid cadences
# are available: 'yearly', 'quarterly', 'monthly', 'weekly', 'daily',
# ('yearly', 'fire') for year-since-fire, or 'timestep' for a grid per model
# step. This produces keys like 'RUSLE_sum_total' and 'delivered_max_total'.
recorder_factory = rusle.default_rusle_recorders(
    grid_variables=('RUSLE', 'delivered'),
    grid_fns=('sum', 'max'),
    grid_timesteps=('total',),
    include_timeseries=True,
)
recorders = recorder_factory(ctx, rain_seq.index[0], rain_seq.index[-1])

# %%

# %% [markdown]
# ### Calibration parameters for this run
#
# The RUSLE simulation and the debris flow model have their own calibration
# parameters (`erosion` and `debris`). They resolve through the same five
# layers as the preprocessing ones — package defaults, then
# `<project>/parameters.json`, `Catchments/<c>/parameters.json`, the event's
# `event.json`, then a one-off call override — with the most specific winning.
#
# You do not need to re-specify anything the PrepareData notebook set: the
# context reads it back.
#
# > **Status:** `erosion` is **live** — the RUSLE P factor, the dNBR
# > severity split and the kinetic-energy rate all take effect here.
# > `debris` is partly wired — its dNBR cutoff and lookup table take
# > effect, its erosion/deposition coefficients do not yet. The
# > preprocessing groups are live too, so the layers this run reads
# > already reflect any overrides you set in PrepareData.

# %%
# What this run resolves, and where each value came from:
record = ctx.parameters()
record.parameters.erosion.support_practice_factor

# %%
# `sources` distinguishes a deliberate value from a defaulted one — the thing
# you will want to know when you revisit these results.
record.sources['erosion.support_practice_factor']

# %%
# `erosion` and `debris` control run-scope outputs, so unlike `topography` and
# `delivery` they can be set at any level, including per event:
# ctx.set_event_parameter_overrides({'erosion': {'support_practice_factor': 0.8}})

# %%
# ...or for a single run, without persisting anything. The resolved record
# is written to provenance.json beside the results, so the outputs say what
# produced them:
# results = rusle.run_usle_simulation(
#     ctx, rain_seq, recorders=recorders,
#     params=ctx.parameters(erosion__support_practice_factor=0.8))

# %% [markdown]
# ### Run the simulation

# %%
# run_usle_simulation runs the whole rainfall period continuously, applying
# the recovery windows internally (the fire-adjusted C/K/SDR layers switch at
# each window boundary). Recovery is not an output dimension — results are a
# single continuous set for this run.
results = rusle.run_usle_simulation(ctx, rain_seq, recorders=recorders)

# %% [markdown]
# ### Baseline (no-fire) simulation
#
# To isolate the fire-attributable component of the erosion, we re-run
# the same simulation using the **unadjusted** C and K factors — i.e. as
# if the catchment had not burned. Outputs land in a sibling
# ``Results_baseline/`` folder so they sit alongside, rather than
# overwriting, the fire-impacted results. Differencing the two gives
# the erosion uplift caused by the fire.

# %%
# The baseline uses the unadjusted C/K factors and the baseline SDR
# (SDR_baseline.tif). These are all produced during PrepareData by
# compute_adjusted_k_c, so no extra preparation is needed here — just build
# a fresh recorder set (recorders carry accumulator state from the fire run)
# and run with use_fire_adjusted=False.
baseline_recorders = recorder_factory(
    ctx, rain_seq.index[0], rain_seq.index[-1])
baseline_results = rusle.run_usle_simulation(
    ctx, rain_seq,
    recorders=baseline_recorders,
    use_fire_adjusted=False,
)

# %% [markdown]
# ### Viewing RUSLE simulation results
#
# One easy, intuitive way to view the rsults is as a daily timeseries of total mass eroded each day. This is embedded within the `results` object created above

# %%
results['erosion_daily_time_series']

# %% [markdown]
# You can also visualise the various outputs.
# - To view the results for the whole catchment as a raster, use `plot_catchment_raster()`
#     - Grids are written to the `Results` folder, named by recorder key
#       (e.g. 'RUSLE_sum_total', 'delivered_max_total').
# - To view results aggregated by subcatchment, use `plot_subcatchments()`
#     - Pass the catchment name, `data_type='Results'`, and the recorder key.
#     - The data is aggregated per subcatchment using the appropriate stat:
#         - Sum for totals (e.g. 'RUSLE_sum_total', 'delivered_sum_total')
#         - Mean for peaks/max (e.g. 'RUSLE_max_total', 'delivered_max_total')
#
# Examples of the different visualisations for our example catchment are shown in the following cells

# %%
# To see a complete picture of sediment eroded across the catchment:
proj.plot_catchment_raster('Results', 'RUSLE_sum_total', ctx=ctx)

# %%
# To see the total sediment eroded across each subcatchment:
proj.plot_subcatchments(catchment=catchment_name, data_type='Results', colour_col='RUSLE_sum_total', ctx=ctx)

# %%
# To see the maximum erosion for any 30-minute period for each cell:
proj.plot_catchment_raster('Results', 'RUSLE_max_total', ctx=ctx)

# %%
# To see the average maximum erosion in any 30-minute period across subcatchments:
proj.plot_subcatchments(catchment=catchment_name, data_type='Results', colour_col='RUSLE_max_total', ctx=ctx)

# %% [markdown]
# Once we've predicted how much sediment has *eroded* from each cell, the final RUSLE step is to work out how much of that eroded sediment actually makes its way downhill and is *delivered* to the stream network.

# %%
# Total sediment delivered to streams over the simulation:
proj.plot_catchment_raster('Results', 'delivered_sum_total', ctx=ctx)

# %%
# Totals delivered from each subcatchment:
proj.plot_subcatchments(catchment=catchment_name, data_type='Results', colour_col='delivered_sum_total', ctx=ctx)

# %%
# Largest mass of sediment delivered during any 30-minute period for each cell:
proj.plot_catchment_raster('Results', 'delivered_max_total', ctx=ctx)

# %%
# Average maximum sediment delivered during any 30-minute period across each subcatchment:
proj.plot_subcatchments(catchment=catchment_name, data_type='Results', colour_col='delivered_max_total', ctx=ctx)

# %% [markdown]
# ## Debris Flow Simulation
#
# Debris flow operates on headwaters only and uses 12 minute rainfall _intensity_ data.
#
# The first thing we need to do is convert the rainfall *depth* values provided by pyraingen, to *intensity* values and then resample to 12-minute intervals
#

# %%
from fire_impacts.sim import convert_rainfall_depth_to_intensity

# %%
rainfall_intensity = convert_rainfall_depth_to_intensity(rainfall_data)
rainfall = aggregate_rainfall_data(rainfall_intensity,rain_data_start,rain_data_end,time_res='12min')
rainfall.rainfall

# %%
# Extract and inspect one replicate:
rain_intensity_seq = rainfall.rainfall[:,9].to_pandas()
rain_intensity_seq
# %% [markdown]
# ### Run the simulation

# %%
df_results = debris_flow(ctx, rain_intensity_seq)

# %% [markdown]
# ### Viewing debris flow simulation results
#
# A table of results for each headwater will be saved to the project's **DebrisFlow** folder. A separate table will also be created with the same results aggregated to subcatchments.
#
# The easiest way to interpret the results is to use the build in visualisation methods: `plot_headwaters()` and `plot_subcatchments()`.
#
# > **Note**: For this example, and in many cases, rainfall intensity values might be below the threshold required to initiate a debris flow in any of the headwaters.

# %%
# To see the calculated critical thresholds for debris flow:
proj.plot_headwaters(catchment_name, 'I12_crit_mean_Year_1', data_type='DebrisFlow', ctx=ctx)

# %%
# The same, aggregated as the average threshold for each subcatchment:
proj.plot_subcatchments(catchment_name, 'DebrisFlow', 'I12_crit_mean_Year_1', ctx=ctx)

# %%
# To see the number of debris flow events in each headwater:
proj.plot_headwaters(catchment_name, 'Year1_num_events', data_type='DebrisFlow', ctx=ctx)

# %%
# And by subcatchment:
proj.plot_subcatchments(catchment_name, 'DebrisFlow', 'Year1_num_events', ctx=ctx)

# %%
# Finally we can view the mass that would form part of a debris flow in each subcatchment:
proj.plot_subcatchments(catchment_name, 'DebrisFlow', 'mass', ctx=ctx)

# %%
